import schemakeyword from './models/schemakeyword.js';
import Queue from 'bull';
import schemaurlpost from './models/schemaurlpost.js';
import delay from 'delay';
const queueKeyWord = new Queue('queueKeyWordApi','redis://127.0.0.1:6379')

const urlVdideo1 = [


    "VinaCapital",
"Vinacap",
"VNCapital",
"VinaCappital",
"VNCappital",
"Quỹ ETF VinaCapital VN100",
"Vina Capital",
"Quỹ đầu tư Vina",
"VinaCapital Vietnam Opportunity Fund",
"Forum One – VinaCapital Vietnam Fund",
"VinaCapital Vietnam Access Fund Limited",
"VinaCapital Ventures",
"Vina Capital",
"Quỹ Đầu Tư Cổ Phiếu Tiếp Cận Thị Trường",
"Quỹ Đầu Tư Cổ Phiếu Tiếp Cận Thị Trường",
"Quỹ Đầu tư Cổ Phiếu Kinh Tế Hiện Đại",
"Quỹ Đầu tư Cân bằng Tuệ Sáng",
"Quỹ Đầu tư Trái phiếu Bảo Thịnh",
"Quỹ Đầu tư Trái Phiếu Thanh Khoản",
"Diehatsu",
"Toyhatsu",
"ĐAI hát su",
"TOI rô ta",
"raize",
"toyota",
"aha move",
"aia vietnam",
"Air pay",
"alma resort",
"alma vietnam",
"Arena Multimedia",
"Bamboo airway",
"bao đậu",
"bao duyệt",
"bảo hiểm metlife",
"bảo hiểm nhân thọ BIDV",
"bảo hiểm nhân thọ",
"bảo hiểm",
"bao hồ sơ",
"bao hs",
"bao hso",
"Bảo Việt Nhân Thọ",
"Bar Son",
"bất động sản sơn kim",
"BAY ZONE",
"Be app",
"Bee app",
"bến phà xác sống",
"bệnh viện hạnh phúc",
"Bệnh viện Hoàn Mỹ",
"bệnh viện quốc tế hp",
"Bệnh Viện Quốc tế Mỹ AIH",
"bệnh viện quốc tế mỹ",
"Bia Ruby đỏ",
"Bia Sư Tử Trắng",
"BIDV chi nhánh Vạn Phúc",
"BIDV core banking lỗi",
"BIDV corebanking",
"BIDV lỗi",
"BIDV metlife",
"Big C",
"Bim Group",
"BIM Hùng Thắng",
"Bim land",
"Bot 39B",
"bột ăn dặm Hipp",
"Bột ăn dặm Organic",
"bột ăn dặm vinamilk",
"Bột giặt Joins",
"Bột giặt NET",
"Bột giặt NETCO",
"Bột giặt Shotz",
"Bot Kiến Xương BOT",
"Bot Kiến Xương Thái Bình",
"bột sữa nhập khẩu",
"Bot Thanh Nê",
"Bùi Quang Ngọc",
"BÙI THỊ HƯƠNG",
"bv hạnh phúc",
"BVQT Hạnh Phúc",
"Cà Ná SB",
"cần tiền",
"cần v.a.y",
"cần vay",
"cảnh báo chiếm đoạt",
"cảnh giác chiếm đoạt",
"CAO Fine Jewellery",
"capita land",
"cắt giảm nhân sự kho vận",
"cắt giảm nhân sự",
"Cầu Thủ Thiêm 2",
"CĐT G NHỔ CÂY XANH",
"Celadon citi gồm ruby emerald diamond",
"CELADON MỘT LÒNG CHUNG SỨC",
"Central Avenue Quy Nhon",
"Central Group",
"Central Retail",
"chai macchiato",
"Cháo Komi",
"cho v.a.y",
"cho vay",
"Chris Blank",
"Chun Byung Ki",
"Chứng khoán HD",
"Chuyển tiền SAHA",
"Citadines Hạ Long",
"Citi Station",
"CL-Thanh Nien",
"CL-Thien Duc",
"cổ phiếu HUT",
"cocobay",
"Come Home",
"Cộng đồng người dùng VIB (Ngân hàng Quốc tế)",
"Công ty 35",
"Công ty cao su Trung Nguyên",
"Công ty cơ khí và công nghiệp hỗ trợ",
"CÔNG TY CỔ PHẦN ĐỒNG GIA",
"Công ty cổ phần Gamuda",
"Công ty cổ phần kết nối nhân tài",
"Công ty Cổ phần Năng lượng Dầu khí Châu Á",
"Công ty Cổ phần Phát triển Dự án Điện gió La Gàn",
"Công ty Cổ phần Quốc tế Cam Ranh",
"CÔNG TY CỔ PHẦN THANH TOÁN QUỐC GIA VIỆT NAM",
"Công ty CP hàng không Tre Việt",
"Công ty Đầu Tư Đỗ Gia",
"Công ty Đỗ Gia Capital",
"Công ty Đỗ Gia Quảng Ninh",
"Công ty Đồng Gia",
"công ty gạch prime Vĩnh Phúc",
"Công ty Novasia Energy",
"Công ty Tâm Thành",
"Công ty TNHH Đỗ Gia Capital",
"CÔNG TY TNHH MỘT THÀNH VIÊN XÂY DỰNG VÀ KINH DOANH NHÀ TRƯỜNG TÍN",
"CÔNG TY TNHH MTV ĐẦU TƯ PHÁT TRIỂN ĐỖ GIA QUẢNG NINH",
"CÔNG TY TNHH TÂM THÀNH",
"CÔNG TY TNHH VĂN LÂM",
"công ty Vịnh thiên đường",
"Cowboy Jack",
"Crown X",
"Crystal Jade Kitchen",
"CTCP Thanh toán quốc gia Việt Nam",
"cửa hàng bipbip",
"cửa hàng kubo",
"cửa hàng lan chi",
"cửa hàng vin",
"cửa hàng win",
"đa khoa hạnh phúc",
"Đai hát su",
"đại học Vin",
"Dai ichi",
"Dai kin",
"Đại Lải",
"Đại Phúc Land bán chui",
"Đại Phúc Land không được cấp phép",
"Đại Phúc Land lừa đảo",
"Đại Phúc Land siết cọc",
"Đại Phúc Land",
"Đại Quang Minh",
"Đặng Quốc Toản",
"đậu nành Soya",
"Đầu tư Phát triển Sản xuất Hạ Long",
"David Riddle tân hiệp phát",
"David Riddle",
"De La Sol",
"đề nghị truy tố 3 cha con ông chủ Tân hiệp phát trần quí thanh",
"ĐH Greenwich",
"Đỗ Cao Bảo",
"Đồ nướng shogun",
"Đoàn Quốc Huy",
"Đoàn Quốc Việt",
"Doãn Quý Đoàn Bamboo",
"dr rùi",
"dr ruồi",
"dr thanh",
"dr win",
"dr. ruoi",
"dr. thanh",
"dự án cocobay",
"Dự án La Gàn",
"dự án Vĩnh Hy",
"dự án vườn quốc gia Núi Chúa",
"đuổi việc",
"Dương Công Minh",
"duyệt nhanh",
"ép bê tê",
"farm nghệ an",
"Foresa Villa Xuân Phương",
"Forland Ben",
"fpt school",
"FPT x Zeit Media",
"FPTTechDay 2023",
"FPTxZeit Media",
"Freeship Extra",
"Fresh & Chill",
"FWD Vietnam",
"G.i.a.o H.a..n.g N.h.a.nh",
"Gamuda Berhad",
"Gamuda City",
"Gamuda Land Bình Dương",
"Gamuda Land HCMC",
"Gamuda Land Ho Chi Minh City",
"Gamuda Land Nam Việt International",
"Gamuda Land Vietnam",
"Gamuda Land",
"Gateway Thao Dien",
"GHN Express",
"Giấc mơ sữa Việt",
"Giải Đua Xe Mô Tô",
"giải ngân ngay",
"giải ngân nhanh",
"giao hang nhanh",
"go Hồng Ngự",
"Go Rạch Giá",
"go Thanh Bình",
"go! Hồng Ngự",
"go! RachGia",
"go! Thanh Bình",
"gogi house",
"Grand Bay Halong",
"Greek Yogurt",
"Green Farm",
"Green Star Sky Garden",
"Green Star",
"grow plus",
"Hạ Long",
"Halong Marina",
"HANH PHUC Hospital",
"hd bank",
"hệ phòng thủ 1170",
"Heritage WestLake",
"highland coffee",
"Highlands coffee",
"him lam",
"hỗ trợ v.a.y",
"hỗ trợ vay",
"Hổ Vằn",
"Hoàng Nam Tiến",
"hoang sa viet nam",
"Hoàng Việt Anh",
"Home Credit",
"Home Paylater",
"Honda Racing Vietnam (HRV)",
"Hưng Lộc Phát",
"Hưng Phát Building",
"Hưng Phát Green Star",
"Hưng Phát Silver Star",
"hưng thịnh",
"ICON 40",
"Intercontinental Halong",
"Intercontinental Phu Quoc",
"ito đồng nai",
"Jack Nguyễn",
"k pub",
"Kem Delight",
"Kem Oze",
"Kem Subo",
"kem Twincows",
"kem vinamilk",
"kem yolo",
"Kenko Haru",
"kẹt tiền",
"không lãi suất",
"Khu đô thị 10B Quảng Ninh",
"Khu Sala",
"KIA MORNING",
"Kia Motors",
"ko lãi suất",
"La Gan offshore wind farm",
"La Gan project",
"LA GAN",
"La Gàn",
"Lagan Wind Power Development Corporation",
"lãi suất thấp",
"lãi thấp",
"lan chi mart",
"lanchi mart",
"lazada cắt giảm nhân sự kho vận",
"lazada cắt giảm nhân sự",
"lazada đuổi việc",
"lazada layoff",
"lazada Sa thải shipper",
"lazada sa thải",
"Le Méridien Saigon",
"le meridien",
"Lê Quốc Minh báo Nhân Dân",
"Lê Quốc Minh",
"Lê Thái Sâm Bamboo",
"LÊ THÀNH LIÊM",
"Lê Thị Trợ Giúp",
"Long Châu",
"love yogurt",
"ls thấp",
"lzd cắt giảm nhân sự kho vận",
"lzd cắt giảm nhân sự",
"lzd đuổi việc",
"lzd layoff",
"lzd Sa thải shipper",
"lzd sa thải",
"Madam Nụ tân hiệp phát",
"Madam Nụ",
"mai kiều liên",
"Mạng 3 chữ",
"mạng fpt",
"manu life",
"Marina Bayfront",
"Marina Square",
"Masan High-Tech Materials",
"masan hightech materials",
"Mascot Beso",
"MẤT TIỀN TỪ ZALO PAY VÀ SENDO",
"MC kool",
"meat deli",
"Mega 6/45",
"Milk Tiger",
"MInh Xoài",
"MINI Cooper",
"mini go",
"miu tai gơ",
"Mộc Châu",
"mon te",
"Ms Hoa TOEIC",
"Ms Hoa",
"Ms.Hoa Giao tiếp",
"Ms.Hoa TOEIC",
"mua góp",
"Mũi Né Summerland",
"muốn v.a.y",
"muốn vay",
"my joy",
"n.ợ chú ý",
"n.ợ x.ấ.u",
"n.ợ x.ấu",
"n.ợ xấu",
"napas bảo trì hệ thống",
"napas chậm",
"napas hack",
"napas khó khăn",
"napas không đăng nhập được",
"napas lỗi",
"napas lừa đảo",
"napas phí cao",
"napas tệ",
"NATIONAL PAYMENT CORPORATION OF VIET NAM",
"National Payment Services Vietnam",
"nền tảng thương mại điện tử",
"Ngân hàng Á Châu",
"ngân hàng Đầu tư và Phát triển",
"ngân hàng HD",
"Ngân hàng Quốc tế",
"ngân hàng SHB",
"Ngân hàng thương mại cổ phần Á Châu",
"ngân hàng VIB",
"ngôi sao phương nam",
"Ngũ cốc B Fast",
"Ngũ cốc Kachi",
"Nguyễn Đăng Quang",
"Nguyễn Hùng Minh",
"Nguyen Jack Nhut Minh",
"Nguyễn kim",
"Nguyễn Minh Hải Bamboo",
"Nguyễn Ngọc Trọng Bamboo",
"NGUYỄN QUỐC KHÁNH",
"Nguyễn Thành Trung",
"NGUYỄN THỊ THANH HÒA",
"Nguyễn Thị Thanh Hương",
"NH quốc tế",
"nh tmcp á châu",
"Nhà hàng shogun",
"Nhà thuốc LC",
"nhà xe phương trang",
"Nhóc kem",
"nhu cầu v.a.y",
"nhu cầu vay",
"nợ chú ý",
"nợ xấu",
"novaland BIDV",
"Novasia Energy",
"núi pháo",
"number 1",
"number one",
"Nước giặt xả Chanté",
"Nước giặt xả Sopa",
"Nước khoáng Blizka",
"Nước khoáng chanh muối Lemona",
"Nước khoáng Quang Hanh Faith vị chanh muối",
"Nước khoáng Quang Hanh",
"Nước khoáng Quảng Ninh",
"Nước khoáng Suối Mơ",
"Nước khoáng Vihawa",
"Nước khoáng Vĩnh hảo",
"Nước khoáng Viviant",
"Nước lau sàn NET",
"Nước rửa chén Homey",
"Nước rửa chén NET",
"Nước rửa chén Sạch",
"Nước rửa tay NETCARE+",
"Nước tăng lực Compact",
"Ocean Star Resort",
"ông thọ",
"Organic Gold",
"oto vin",
"Park Hyatt Phu Quoc",
"paula choice",
"Pedia Kenji",
"phạm nhật vượng",
"Phạm Thị Nụ",
"Phạm Văn Tài",
"Phan Đức Tú",
"PHAN MINH TIÊN",
"Phil café Việt",
"Phinn café",
"Phó giám đốc David Riddle",
"Phở Kokomi",
"Phô mai xuxu",
"phố ngon 37",
"Phó TGĐ Bamboo airway",
"phổ thông fpt",
"phòng khám Hạnh Phúc",
"Phu Quoc Marina",
"Phú Quốc",
"phúc long",
"platinum premium",
"Poly K-Beauty",
"Power 6/55",
"Power cam đào",
"power chocolate",
"power socola",
"prime Vĩnh Phúc",
"Quốc tế Hạnh Phúc",
"Quý anh Lê Quốc Minh",
"Quy Nhơn Melody",
"rai ze",
"Raize SUV",
"Reddi Mobicase",
"Regent Phu Quoc",
"resort alma",
"resort bò sữa",
"ri dielac",
"Robot Beso",
"S.H finance",
"Sa thải shipper",
"sa thải",
"Sadora Myanmar",
"SAHA APP",
"SAHA WEB",
"Sailing club Halong",
"Sailing club Phu Quoc",
"Sala Thủ Thiêm",
"Seasons Avenue",
"Sen do",
"sếp Tiến",
"Serenity Sky Villas",
"shin han finance",
"Shinhan finance",
"Shogun Janpanese street BBQ",
"Shopee Express",
"Shopee Food",
"shopee pay",
"Shophouse Phú Quốc",
"siêu thị bipbip",
"Siêu thị GO",
"siêu thị kubo",
"siêu thị lan chi",
"siêu thị vin",
"siêu thị win",
"Skoda Kodiaq việt nam",
"Skoda Kodiaq",
"Skoda việt nam",
"Smart Cloud",
"son kim land",
"sonkim land",
"STC Hero",
"STTT tổ yến",
"Su su",
"sữa 9 loại hạt",
"sữa a2",
"sữa ADM",
"sữa bịch vinamilk",
"sữa bò",
"sữa chị liên",
"sữa chua kefir",
"sữa chua LoveYogurt",
"sữa chua su su",
"sữa chua susu",
"sữa chua uống su su",
"sữa chua vinamilk",
"sữa đặc phương nam",
"sữa đặc tài lộc",
"sữa đặc vianmilk",
"sữa đậu nành soya",
"sữa flex",
"sữa Green Farm",
"sữa greenfarm",
"Sữa hạt ngũ cốc B Fast",
"sữa hạt",
"sữa hero",
"sữa hipp bò",
"sữa hipp dê",
"sữa Hipp",
"sữa hoàn nguyên",
"sữa MC",
"sữa ông thọ",
"sua optimum",
"sữa Organic",
"sữa platinum",
"sua probi",
"Sữa tắm La Petal",
"Sữa Tổ Yến",
"sữa tươi tổ yến",
"Sữa tươi Vinamilk 100%",
"sữa tươi vinamilk",
"sữa Twincows",
"sữa vinamilk",
"Summer Sea",
"sumo bbq",
"Super nut",
"Sure Diecerna",
"Sure Prevent",
"tài chính home",
"tài chính shinhan",
"Tâm sự giao hàng cùng GHN",
"tân hiệp phát",
"tận tâm 100%",
"Tập đoàn Central",
"Tập đoàn Copenhagen Infrastructure Partners",
"Tập đoàn Copenhagen Offshore Partners",
"tập đoàn Hưng thịnh",
"Tập đoàn năng lượng Asiapetro",
"tập đoàn sơn kim",
"taxi GSM",
"thành viên HĐQT Bamboo airway",
"The 9 Stellar",
"The Coffee Inn",
"The Crest Residence",
"The Galleria Residence",
"The Garden - Hà Nội",
"The Golden Spoon",
"The Golden Star",
"The Metropole Thu Thiem",
"The Nassim",
"The Opera Residence",
"The Peak Garden",
"The sherpa",
"thẻ tín dụng VIB",
"thẻ vib",
"thiên địa hội",
"thiếu tiền",
"tiền góp",
"Tiêu Yến Trinh",
"Tổng biên tập báo Nhân Dân",
"TỔNG CÔNG TY ĐÔNG BẮC",
"Tổng Giám đốc Bamboo airway",
"top market",
"tops market",
"toy gian lận an toàn",
"toyhatsu gian lận túi khí",
"toyota gian lận",
"toyota vietnam",
"toyota wigo",
"trả góp",
"trà xanh không độ",
"Trần Bá Dương",
"Trần Hùng Huy",
"TRẦN MINH VĂN",
"trần ngọc bích",
"trần quí thanh",
"trần quý thanh",
"trần uyên phương",
"Trần Văn Tâm Sự",
"Trần Viên Ngọc Oanh",
"Trần Viên Ngọc Trân",
"Trinh Tieu",
"Trường F",
"Trương Gia Bình",
"Trường Hải",
"truong sa viet nam",
"truy tố ông chủ tân hiệp phát",
"truy tố trần quí thanh",
"Ứng dụng SAHA",
"Union District",
"Uniqlo Vietnam",
"Uniqlo VN",
"v.a.y gấp",
"v.a.y nhanh",
"v.a.y tiền",
"v.a.y tiêu dùng",
"v.a.y trả góp",
"v.a.y v.ố.n",
"Vạn Phúc City bán chui",
"Vạn Phúc City không được cấp phép",
"Vạn Phúc City lừa đảo",
"Vạn Phúc City siết cọc",
"Vạn Phúc City",
"Vạn Phúc Group",
"Vàng bạc Đá quý Phú Nhuận",
"vay gấp",
"vay nhanh",
"vay tiền mặt",
"vay tiêu dùng",
"vay trả góp",
"vay vốn",
"veloz cross",
"Vi na Miu",
"Viên Diệu Hoa",
"Việt Sugar",
"Vietnam Airlines",
"Vietnam Motor Racing",
"vin eco",
"Vin group",
"vin gsm",
"Vina café",
"vinamilk 100",
"Vinamilk Hipp",
"vinamilk organic",
"vinamilk power",
"Vợ ông Thanh",
"vượng vin",
"Wake up Café",
"Wake-up 247",
"win eco",
"win mart",
"win pharm",
"Xổ số kiểu Mỹ",
"xổ số tự chọn",
"Xúc xích heo cao bồi",
"Xúc xích Ponnie",
"Yangon Myanmar Centre",
"Yaris cross",
"Yu tang",
"zalo pay",
"ZeitMedia FPT",
"ZeitMedia x FPT",
"acb",
"Ahamove",
"aiavietnam",
"AIAVietnamLifeInsurance",
"aih",
"airpay",
"Alma",
"almaresort",
"ArenaMultimedia",
"ashima",
"Asiapetro",
"Auman",
"avanza",
"BaoVietnhantho",
"BAYZONE",
"bebike",
"becar",
"beFood",
"BeGroup",
"beride",
"bhnt",
"BIC",
"BID",
"BIDV",
"BigC",
"Bimland",
"Bingo18",
"BMW",
"BSC",
"btecfpt",
"CapitaDNA",
"capitaland",
"capitalland",
"Carens",
"Carnival",
"centralretailvietnam",
"centralvietnam",
"Cerato",
"Chin-su",
"CIP",
"CL-Vista",
"Cocobay",
"Cocofresh",
"Colos",
"ColosGold",
"Comehome",
"COP",
"Cowboy",
"CrystalJadeKitchen",
"CVLife",
"D1Mension",
"Dai-ichi",
"Daihatsound",
"Daihatsu",
"ĐạihọcFPT",
"Daiichi",
"DaiichilifeVietNam",
"DaiichiVietNam",
"daiichivn",
"Daikin",
"daikinvietnam",
"daikinvn",
"Daiyota",
"daruma",
"DavidRiddle",
"DEFINE",
"delasol",
"DelightNgonMeSay",
"deliverynow",
"Diecerna",
"Diehatsu",
"Dielac",
"DielacGrowPlus",
"DielacPedia",
"DieuduongHoanMy",
"DisneyPNJ",
"ĐQM",
"dr.win",
"Dropii",
"Droppi",
"Droppii",
"dropshipping",
"drrui",
"drruoi",
"drthanh",
"Emart",
"EV6",
"F.Studio",
"Foxpay",
"FPoly",
"FPT",
"fptedu",
"fptplay",
"FPTPolytechnic",
"Fpts",
"FPTTechDay2023",
"FPTU",
"FPTxZeitMedia",
"Frontier",
"Fschool",
"fsoft",
"Ftel",
"FTICO",
"FUNiX",
"Fuso",
"FWDbảohiểm",
"FWDbảohiểmdễhiểu",
"GAMUDA",
"Gamudacity",
"GamudaLandVN",
"GamudaVN",
"GHN vietnam",
"giacmosuaviet",
"giaohangnhanh",
"go!RachGia",
"Gogi",
"goldsoy",
"goRachGia",
"hanhphuchospital",
"hdb",
"HDBANK",
"hds",
"herosusu",
"Highlands",
"himlamland",
"Hipp",
"hippvietnam",
"hippvn",
"homecredit",
"homecreditvn",
"HTN",
"hunghtinhland",
"HungThinhCorp",
"hungthinhgroup",
"hungthinhincons",
"Hutong",
"ICON40",
"ila",
"IMAP",
"IMAPers",
"iphở",
"ishushi",
"isushi",
"keno",
"KIAMORNING",
"kichi-kichi",
"Kichi",
"kichikichi",
"kpub",
"layoff",
"linkco",
"lynkco",
"MadamNụ",
"Manulife",
"ManulifeMOVE",
"ManulifeVietnam",
"ManulifeVN",
"Manwah",
"Masan",
"MasRacing",
"Massan",
"MCH",
"meatdeli",
"metlife",
"MilkTiger",
"miltiger",
"minigo",
"mml",
"monte",
"MSN",
"msr",
"NAPAS",
"Napas247",
"Napnangluonggiutraidatxanh",
"NgayTieuHoaTheGioi",
"NgôiSaoPhươngNam",
"nguyenkim",
"nhockem",
"nowdelivery",
"nowfood",
"nowvn",
"number1",
"numberone",
"nuoctraicayVfresh",
"Optima",
"Optimum",
"Optimumgold",
"ozela",
"panasonic",
"Pharmacity",
"phomaimilktiger",
"phomaizott",
"photghn",
"phuclong",
"PNJ",
"PNJdiamond",
"PNJDisney",
"PNJGold",
"PNJSilver",
"PNJWatch",
"Polytechnic",
"Powercamđào",
"powerchocolate",
"powersocola",
"probi",
"ProbiPedia",
"Proby",
"PropertyX",
"Prudential",
"Prudentialvietnam",
"Prudentialvn",
"PTCĐFPTDaNang",
"Quoris",
"resortalma",
"Ridielac",
"ridielacgold",
"ridilac",
"Sadora",
"Sarica",
"Sarimi",
"Sarina",
"Saritown",
"Saroma",
"sdnvinamilk",
"Sedona",
"Seltos",
"Sendo",
"SHB",
"SHBBANK",
"ShinhanFc",
"ShinhanFinance",
"shopee",
"ShopeeFood",
"Shopeepay",
"Skillking",
"skoda",
"Sofic",
"Software",
"Sogal",
"Soluto",
"Sonet",
"Sorento",
"SOVICO",
"Sportage",
"Startalk",
"StylebyPNJ",
"Suachuauongmensong",
"SuachuauongProbi",
"SuachuaVinamilk",
"suadactailoc",
"SữaĐậuNànhHạnhNhân",
"sữaflex",
"SữaHero",
"suamocchau",
"suatuoivinamilk",
"suatuoivnm",
"suavinamilk",
"suavnm",
"SữaVNMTổyến",
"superNut",
"SuperSuSu",
"surediecerna",
"Susu",
"susuhero",
"SuSuIQ",
"susuvinamilk",
"susuvnm",
"SVFC",
"Sycamore",
"Synnex",
"Syrena",
"T-Pay",
"Talentnet",
"Tasco",
"techday",
"techday2023",
"Telluride",
"TheCoffeeInn",
"THILOGI",
"Thiskyhall",
"THISO",
"Thisofic",
"THISOMall",
"THISORETAIL",
"thoaimaitrainghiemguz",
"THP",
"Topenland",
"topsmarket",
"Towner",
"Toyhatsu",
"TPay",
"TrainghiemmoiGiatrimoi",
"Uniqlo",
"Uniqlovn",
"V.I.B",
"veloz",
"vesiProbi",
"Vfresh",
"VIB",
"VIBBANK",
"vietlot",
"vietlott",
"Vietsugar",
"Vinamilk",
"Vinbus",
"Vincom",
"vincommer",
"vineco",
"VinFast",
"Vingroup",
"Vinhomes",
"vinmart",
"vinmec",
"vinpearl",
"Vinschool",
"Vinuni",
"vmmhero",
"VMRC",
"vnm",
"vnmhappy",
"VNMHero",
"vnmsusu",
"vnmzori",
"Vuvuzela",
"wincommer",
"winpharm",
"Wintel",
"yaris",
"yoko",
"yomilk",
"Yutang",
"zalopay",
"ZeitMediaxFPT",
"Zenity",
"zott",
"ZottMilkTiger",
"Member of the EQuest Education Group",
"tập đoàn giáo dục",
"Nguyễn Quốc Toàn",
"Annabelle Vultee",
"Nguyễn Thanh Sơn",
"Nguyễn Thị Tuyết Lan",
"Đàm Bích Thuỷ",
"George Aitken",
"Trần Quốc Khánh",
"J. David Armstrong Jr.",
"Đàm Quang Minh",
"khoa học STEM",
"Trường liên cấp Newton",
"Trường ngôi sao Hà Nội",
"Trường tiểu học công nghệ giáo dục Hà Nội",
"Trường St. Nicholas",
"Alpha School",
"Happy School",
"THPT Victory",
"Giáo dục thực nghiệm Victory",
"Canada - Vietnam kindergarten",
"Canadian International School Bilingual",
"Canadian International School CIS (Vietnam)",
"Trường tiểu học THCS THPT THPT Albert Einstein",
"Đại học Phú Xuân",
"Đại học Broward Vietnam",
"Trường Kinh doanh Sài Gòn (SBS)",
"Cao đẳng Việt Mỹ",
"Bách khoa Sài Gòn",
"Trường Ivy Global",
"VATC Anh ngữ Việt Mỹ",
"CIS (Vietnam)",
"khoa học - toán - tiếng Anh",
"Trường Song Ngữ Quốc Tế Canada BCIS",
"AES - Albert Einstein School ",
"CVK - Trường Mầm Non Canada - Việt Nam",
"Newton Grammar School",
"Trường THCS - THPT Newton",
"Trường Tiểu học I-sắc Niu-tơn",
"Trường Tiểu Học Newton Goldmark",
"Trường Phổ thông Liên cấp Newton Vĩnh Phúc",
"Trường THPT Victory Sài Gòn",
"Trường THPT Victory Củ Chi",
"Trường ĐH Phú Xuân",
"Trường Trung cấp Bách Khoa Sài Gòn",
"Saigon Business School",
"Ivy Global School",
"Tập đoàn giáo dục tư nhân",
"Trương Hoàng Nam",
"Phạm Thanh Bình (Ngôi sao Hà Nội)",
"mắt kính Anna",
"mắt kính A",
"mắt kính ăn năn",
"mắt kính án nà",
"mắt kính tử tế",
"Kính anna",
"Kính ana",
"Ânna",
"mắt kính Anna T Phạm",
"Trường Tiểu Học và Trung Học Cơ Sở Newton 5",
"FWD",
"Bảo hiểm tai nạn",
"Bảo hiểm hỗ trợ viện phí",
"Đại an minh tâm",
"Bảo hiểm bệnh hiểm nghèo 2.0",
"Bảo hiểm miễn đóng phí bệnh hiểm nghèo 2.0",
"Bảo hiểm miễn đóng phí nâng cao 2.0",
"Bảo hiểm sức khỏe 2.0",
"Bảo hiểm tai nạn",
"Bảo hiểm trợ cấp nằm viện",
"Bảo hiểm tử vong và thương tật",
"Nâng tầm vị thế 2.0",
"#VinaCapital",
"#VCFM",
"#abetterlifeathome",
"#bhsgroup",
"#bimland",
"#buucucGHN",
"#ChipContactless",
"#comehomescvivocity",
"#comehomevietnam",
"#GHN",
"#ghnexpress",
"#GHNHCM",
"#ghnhn",
"#giaohangnhanh",
"#goldengate",
"#kichikichi",
"#laithuskoda",
"#LifeWear",
"#londonex",
"#MadamNu",
"#NAPAS",
"#NAPAS247",
"#PNJ",
"#Shinhanfiance",
"#Skoda",
"#skodavietnam",
"#Superb_2024",
"#tamsugiaohangcungghn",
"#tapchitrading",
"#taychayghn",
"#taychaygiaohangnhanh",
"#thunglungthanhxuan",
"#UNIQLOHanoi",
"#UNIQLOHCMC",
"#UNIQLOVN",
"#VietQR",
"#kinhmatanna",
"#FWDBảohiểmdễhiểu",
"#FWDSốngđầytừhômnay",
"#FWDSớmbảovệ",
"#FWDBaohiemdehieu",
"#FWDSốngdầytừhômnay",
"#FWDSombaove",
"#FWDCelebrateLivingStory",
"#FWDTimetoPlay",
"#FWDAgencyKickoff2024",
"#TrailblazerAwards2024",
"#FWD",

"EQuest",
"A_member_of_EQuest_Education",
"Accredited",
"ANALYC lừa đảo",
"ANALYC phốt",
"App Cake",
"BeFinancial",
"Cake bank",
"Cake by VPBank",
"Cognia",
"CÔNG TY CỔ PHẦN GIÁO DỤC EQUEST",
"Công ty Đỗ Gia Capital",
"Công ty TNHH Đỗ Gia Capital",
"DogiaCapital",
"Dự án 10B",
"duan10B",
"Dwight",
"Dwight School Hanoi",
"dwightschool",
"dwightschoolhanoi",
"DwightSchoolHanoiSparkOfGenius",
"EQuest Education Group",
"EQuest_Education",
"EQuest_Education_Group",
"EQuest_Group",
"GKFX lừa đảo",
"GKFX phốt",
"GKFX Prime lừa đảo",
"GKFX Prime phốt",
"GKFXPrime lừa đảo",
"GKFXPrime phốt",
"Khu đô thị 10B",
"LanvinhHaLong",
"NextGen AI Bank",
"Ngân hàng AI Cake",
"Ngân hàng số Cake",
"Ngân hàng số Cake by VPBank",
"Ngân hàng trí tuệ nhân tạo Cake",
"sàn lừa đảo",
"Tập đoàn Giáo dục EQuest",
"Trường Dwight",
"Văn Phú Invest",
"vanphuinvest",

"#EQuest",
"#A_member_of_EQuest_Education",
"#Accredited",
"#BeFinancial",
"#Cognia",
"#DogiaCapital",
"#DSH",
"#duan10B",
"#Dwight",
"#dwightschool",
"#dwightschoolhanoi",
"#DwightSchoolHanoiSparkOfGenius",
"#EQuest_Education",
"#EQuest_Education_Group",
"#EQuest_Group",
"#LanvinhHaLong",
"#vanphuinvest",


// "Quỹ Đầu Tư Cổ Phiếu Tiếp Cận Thị Trường",
// "Vina Capital",
// "100 plus",
// "10diemantam",
// "11BET",
// "1212SANG0D",
// "1212TOI0D",
// "1212TRUA0D",
// "12SIEUSHIP",
// "1H",
// "1Housing",
// "1ID",
// "1MG",
// "1trieulynuoc0d",
// "20TỷLợiKhuẩn",
// "2870 tại cần giờ",
// "3 khỏe",
// "3 miền",
// "30 sai",
// "30 Shine",
// "30sai",
// "30Shine",
// "37str",
// "3Miền",
// "40NămMangLạiNụCười",
// "500 Pizzeria",
// "5150 triathlon",
// "584 Nha Trang",
// "66FREESHIP",
// "789 club",
// "789club",
// "8X Đầm Sen",
// "8X Plus",
// "8X Rainbow",
// "8X Thái An",
// "91 Phạm Văn Hai",
// "91 pvh",
// "9View Apartment",
// "9x An Sương",
// "9x Hóc Môn",
// "9x Quy Nhơn",
// "Abbott",
// "abbottgrow",
// "AbbottGrowGold",
// "abetterlifeathome",
// "abt",
// "ACB",
// "acecook",
// "acecook viet nam",
// "acecookvietnam",
// "ACG",
// "ADECCO",
// "adeccovietnam",
// "Adidas Viet Nam",
// "Adidas Vietnam",
// "Adidas VN",
// "ads shopee",
// "adslazada",
// "adslzd",
// "adsshopee",
// "adstiki",
// "adstikimall",
// "adstikivietnam",
// "adstikivn",
// "adstiktok",
// "Aeon",
// "AeonEshop",
// "AEONMall",
// "Aeonvietnam",
// "AGR",
// "agribank",
// "Ahamovevietnam",
// "Ahamovevn",
// "AIA",
// "aia bảo hiểm",
// "aia bh",
// "Air-condition",
// "AirPaydieubatngothang6",
// "AirPaydoitenShopeePay",
// "AirPayShopeePay86",
// "airpayvietnam",
// "airpayvn",
// "Ajingon",
// "aka",
// "aka house",
// "akahouse",
// "Al Fresco",
// "Alfresco",
// "Allnewmazda3",
// "alma",
// "ALMAZ",
// "alonhadat",
// "Alpha",
// "Alpha Town",
// "alpha trading hub",
// "am tran",
// "am tran điện quang",
// "am tran rạng đông",
// "am tran TLC",
// "American Polytechnic College",
// "Amerphaco",
// "Amor Riverside Villas",
// "An Cường",
// "An Gia",
// "An Khang",
// "ana mandara đà lạt",
// "Ana Mandara Villas Dalat",
// "AnCungTikTok",
// "Anderson Park",
// "Andy Han Suk Jung",
// "anfagrow",
// "ANGIA GROUP",
// "AnGia28",
// "AnGiaApp",
// "AnGiaGroup",
// "AngiaInvestment",
// "AnGiaLand",
// "AnGiaPlus",
// "AnGiaRiverCity",
// "AnGiaRiverPanorama",
// "AnGiaRiverside",
// "AnGiaSignial",
// "AnGiaSkyline",
// "AnGiaStar",
// "anh ngữ apax",
// "anh ngữ apollo",
// "anh ngữ ila",
// "anh ngữ vus",
// "anh ngữ yola",
// "anonha_contest",
// "anonhacungngon",
// "apax",
// "apax leaders",
// "apollo",
// "appFuta",
// "appvietlott",
// "aquafina",
// "Aquarius",
// "Aquatex",
// "Ariel",
// "Armephaco",
// "ASCUEX Vietnam",
// "ashima",
// "Asiapetro",
// "Astral",
// "AstralCity",
// "ATH",
// "Atome",
// "Ba Gác",
// "Bắc Âu auto",
// "bác quang",
// "Bách hoá XANH",
// "Bách hóa xanh",
// "bae min",
// "baemin",
// "BAEMIN_SharkAn",
// "baemin2tuoi",
// "Baemin3tuoi",
// "baeminapp",
// "baeminbus",
// "BAEMINDANANG",
// "BAEMINHaiPhong",
// "BAEMINHaLong",
// "BAEMINHoiAN",
// "baeminkichent",
// "baeminmart",
// "BaeminNgot",
// "Baeminsinhnhatdieuky",
// "baeminstudio",
// "BAEMINTopTrending",
// "baeminvietnam",
// "baeminvn",
// "Bãi tiên Nha Trang",
// "Bamboo Capital",
// "BambooCapital",
// "Ban lãnh đạo",
// "Bàn ủi panasonic",
// "Banger",
// "Bánh ăn dặm Gerber",
// "bánh Gerber",
// "Bánh mì phúc long",
// "banhangcunglazada",
// "Bao bì AP",
// "bao bì Packamex",
// "bao bì Tín Thành",
// "Bão Flash Sale 1k",
// "Bảo hiểm AIA",
// "Bảo hiểm Bảo Việt",
// "Bảo hiểm BSH",
// "bảo hiểm bv",
// "bảo hiểm dai-ichi life",
// "bảo hiểm manulife",
// "Bảo hiểm nhân thọ aia",
// "bảo hiểm nhân thọ dai-ichi life",
// "bảo hiểm nhân thọ manulife",
// "bảo hiểm nhân thọ prudential",
// "bảo hiểm petrolimex",
// "bảo hiểm prudential",
// "Bảo hiểm xăng dầu",
// "Bảo Lộc Sapung Rescidences",
// "Bảo Tín Minh Châu",
// "Bảo Việt Bảo Hiểm",
// "Bao Viet Insurance",
// "Bảo Việt life",
// "bảo việt nt",
// "Bảo Việt sức khỏe",
// "BAO50",
// "baobimoi",
// "baosalebomtan",
// "baotinminhchau",
// "bar son",
// "Baria City Gate",
// "Baria CityGate",
// "Base.vn",
// "Basta",
// "Basta Hiro",
// "BẤT ĐỘNG SẢN AN GIA",
// "bất động sản cát tường",
// "Bất động sản Hưng Thịnh",
// "bất động sản khang điền",
// "bất động sản Nam Long",
// "bất động sản phú long",
// "bất động sản thắng lợi group",
// "batdongsan",
// "batdongsan.com",
// "BatDongSanPhatDat",
// "Bầu Hiển",
// "Bauer Petit",
// "bc",
// "BCG",
// "BCGEnergy",
// "BCGLand",
// "bds an gia",
// "BDS Dat Xanh",
// "BĐS HƯNG THỊNH",
// "BDS Nam Long",
// "BĐSAnGia",
// "Be",
// "Be Delivery",
// "be food",
// "BE GIAO HÀNG",
// "beAirport",
// "beamin",
// "Beauty In The Pot",
// "beDeliver",
// "BEDELIVERY",
// "bedicho",
// "Bee",
// "bee food",
// "beedeliver",
// "beedelivery",
// "beefood",
// "Beesky",
// "befood",
// "beGiaoHàng",
// "belàtới",
// "bến phà xác sống",
// "Bệnh viện Giao thông Vận tải",
// "Bệnh viện GTVT",
// "bệnh viện hoàn mỹ",
// "bệnh viện quốc tế hạnh phúc",
// "bệnh viện tâm anh",
// "bệnh viện vinmec",
// "Bennhautronduong",
// "benphaxacsong",
// "bếp điện",
// "bếp điện pana",
// "bếp điện panasonic",
// "Bếp Quán",
// "bếp từ pana",
// "Bếp từ panasonic",
// "beship",
// "beShopping",
// "Bésiêunhân",
// "Best Express",
// "bestexpress",
// "bestexpressvietnam",
// "bestexpressvn",
// "bestincvietnam",
// "betagen",
// "bh aia",
// "bh bảo việt",
// "bh bv",
// "bh dai-ichi life",
// "bh manulife",
// "bh prudential",
// "BHX",
// "bi food",
// "Bia Việt Hà",
// "bibica",
// "Biên Hòa New City",
// "Bien Hoa Universe Complex",
// "biệt thự An Viên Nha Trang",
// "Biệt thự Lê Lai",
// "biệt thự sinh thái Nam Cầu Phủ Hà Tĩnh",
// "Biệt Thự Việt Trang",
// "BietDoiPhaiManhShopee",
// "bifood",
// "Big C An Phú",
// "Big C Âu Cơ",
// "big c Hà Đông",
// "big c Lê Trọng Tấn",
// "Big C Thảo Điền",
// "Big C Việt Nam",
// "Big homes",
// "Bighomes",
// "bikipBAEMIN",
// "bim group",
// "bim land",
// "bimgroup",
// "bimland",
// "Bình đun panasonic",
// "Bình thủy điện",
// "bình thủy panasonic",
// "Bip bip",
// "Bipbip",
// "Bitas",
// "Bitis",
// "BK8",
// "Blue Exchange",
// "Bluesky 120S",
// "Blum",
// "BM Windows",
// "BMP",
// "BMW",
// "bò cụng",
// "bò húc",
// "Bộ sưu tập Cà Phê Chai",
// "boba",
// "Bobapop",
// "Bobby",
// "BonCha",
// "Bóng đá nữ Thái Nguyên",
// "bóng đèn",
// "bóng đèn điện quang",
// "bóng đèn rạng đông",
// "bóng đèn TLC",
// "Boo VN",
// "BOOM BOOM",
// "Boost Optimum",
// "Bosch",
// "Bostonmex",
// "Bột ăn dặm Optimum Gold",
// "Bột ăn dặm Organic Gold",
// "Bột ăn dặm Vinamilk Optimum",
// "Bột ăn dặm Vinamilk Optimum Gold",
// "Bột ăn dặm Vinamilk Organic",
// "Bột ăn dặm Vinamilk Organic Gold",
// "Bột Dinh Dưỡng Vinamilk",
// "Bột giặt NET CARE",
// "botandamGERBER",
// "Bòtươivui",
// "Brandt",
// "british council",
// "BT Markets",
// "BT-50",
// "BT50",
// "BTMC",
// "BTMC JEWELRY",
// "BTSGojek",
// "Buatruanore",
// "BuaXe5K",
// "BuaXuaMaDoi",
// "BUCHER",
// "Bùi Ngọc Bảo",
// "Buk buk",
// "Bukbuk",
// "Burine",
// "Buslinefuta",
// "Bưu chính Viettel",
// "BƯU ĐIỆN VIỆT NAM",
// "buuchinhViettel",
// "buucucbest",
// "buucucGHN",
// "bưucụcghtk",
// "buudienvietnam",
// "bv aih",
// "bv hoàn mỹ",
// "bv nhân thọ",
// "bv quốc tế hạnh phúc",
// "bv tâm anh",
// "bvnt",
// "C&B",
// "C2 Milktea",
// "C2Milktea",
// "cà phê Phúc Long",
// "Cà phê Trung Nguyên",
// "Các dự án DNP Water",
// "Cadia Phát Đạt",
// "Cadia Quy Nhon",
// "cadia quy nhơn",
// "Calo Sure",
// "Calokid",
// "CaloSure",
// "CalosureGold",
// "Cam Ranh",
// "Cam Ranh Mystery Villas",
// "Camera Viettel",
// "Camera VNPT",
// "CamRanhMystery",
// "Căn Hộ Biển An Viên Nha Trang",
// "Cảng Quảng Ninh",
// "Cảng tàu khách Quốc tế Hạ Long",
// "cangigrabnay",
// "CangtaukhachHaLong",
// "Cănhộdulịchbiển5saoVũngTàu",
// "Canifa",
// "CanteenKhongXaiTienMat",
// "Canxi Pro",
// "Cao đẳng công nghệ thông tin",
// "Cao đẳng công nghệ TP HCM",
// "Cao đẳng Lý Tự Trọng",
// "Cao đẳng Nova",
// "Cao đẳng Thực hành FPT",
// "Cao đẳng Văn Lang",
// "Cao đẳng Việt Mỹ",
// "cao ốc Sài Gòn M&C",
// "caodangcntt",
// "CaoDangNova",
// "CaodangVietMy",
// "Cáp FPT",
// "Cap House",
// "capital land",
// "Capitaland",
// "CapitaLandDevelopment",
// "CapitaLandDevelopmentVietnam",
// "Carabao",
// "Carpla",
// "Casa Marina",
// "Casa Marina Mũi Né",
// "Casino Corona Phú Quốc",
// "Casper",
// "Casper Việt Nam",
// "Câu lạc bộ bóng đá Hà Nội",
// "CayDealTramCode",
// "CBRE",
// "Cece Box",
// "Cecebox",
// "CELADON SPORTS & RESORT CLUB",
// "CeladonCity",
// "Cen homes",
// "Cen land",
// "cenhome",
// "Cenhomes",
// "Cenland",
// "central park",
// "Centre Point",
// "Cerato",
// "cerelac",
// "cghl",
// "CH Markets",
// "Chà Là",
// "Chấm công & Tính lương",
// "chamdinhsinhloi",
// "ChamMocLenSan",
// "Champarama Resort",
// "ChamparamaResort&Spa",
// "CHAODANANG",
// "chất lượng gạch CMC",
// "chất lượng nước dnp water",
// "Chất lượng Six senses ninh vân bay",
// "Cheering Beer",
// "Chemtech",
// "chịđạiSendo",
// "ChiecDeal0d",
// "ChiecDealAnToan",
// "ChiecDealDzuiDze",
// "Chienbinhtantam",
// "chieu pha",
// "chieu pha điện quang",
// "chieu pha rạng đông",
// "chieu pha TLC",
// "Chipo",
// "Chixmax",
// "Chờ ngày ra xe",
// "Chợ Sen đỏ",
// "chợ tốt",
// "Chomoinguoi",
// "Chongayraxe",
// "chonlazadathoi",
// "Chonmatguivang",
// "ChoTetGrabMart",
// "chotuoigrabmart",
// "Christopher Randy Stroud",
// "Chủ tịch CLB Hà Nội",
// "Chủ tịch Hà Nội FC",
// "Chủ tịch HĐQT Bamboo airway",
// "chủ tịch HđQT vingroup",
// "Chủ tịch Nguyễn Bá Sáng",
// "chùa Linh Thông",
// "Chung Cư 440 Vĩnh Hưng",
// "Chung cư khu Tên Lửa",
// "chứng khoán MBB",
// "Chứng khoán SHB",
// "Chứng khoán SHS",
// "Chuyenxehuongnghiep_ITC2023",
// "CiHMS",
// "Citi",
// "Citizen.TS",
// "CJ Cầu tre",
// "CL Việt Nam",
// "CLB Hà Nội",
// "CMC",
// "CMC CVT",
// "CMC Tiles",
// "cô gái hà lan",
// "Cổ phần Giải pháp Thanh toán",
// "Cổ phiếu CVT",
// "co phieu dat xanh",
// "co phieu DXG",
// "cố phiếu ecopark",
// "Cổ Phiếu FGO",
// "Cổ phiếu NVT",
// "cổ phiếu Phú Long",
// "cổ phiếu tpp",
// "cổ phiếu VND",
// "Cọ Xanh",
// "co.op mart",
// "co.opmart",
// "coc coc",
// "cóc cóc",
// "côc côc",
// "cốc cốc",
// "cọc cọc",
// "Cocacola Energy",
// "cocccoc",
// "coccoc",
// "cốccoc",
// "Coccoc Browser",
// "coccoc mobile",
// "coccoc.com",
// "CốcCốcCareers",
// "cococ",
// "cocofresh vnm",
// "Coffee House",
// "cogaihalan",
// "Colliers",
// "Colos DHA",
// "Colos Gold",
// "Colos Opti",
// "ColosBaby",
// "ColosBabyIQ",
// "colosDHA",
// "ColosFreshMilk",
// "Colosgain",
// "ColosIgG24h",
// "Colosopti",
// "comehomescvivocity",
// "comehomevietnam",
// "compact",
// "Compact",
// "compact điện quang",
// "công nghệ Vinconnect",
// "Công ty AIA",
// "Công ty bán lẻ FPT",
// "Công ty Bảo Việt",
// "Công ty bia Việt Hà",
// "công ty chứng khoán FPT",
// "công ty CMC",
// "Công ty cổ phần chứng khoán VNDirect",
// "Công ty cổ phần Chứng khoán VPS",
// "Công ty Cổ phần Công nghiệp năng lượng Ninh Thuận",
// "Công ty Cổ phần Dầu khí Đông Phương",
// "Công ty Cổ phần Đường Quảng Ngãi",
// "công ty cổ phần FPT",
// "Công ty Cổ phần Giày Việt",
// "Công ty Cổ Phần Hóa dầu Quân đội",
// "Công Ty Cổ Phần Kinh Doanh Và Đầu Tư Việt Hà",
// "công ty cổ phần Nhựa Đồng Nai",
// "Công ty cổ phần Nông nghiệp Trường Hải",
// "Công ty cổ phần Quản lý quỹ BVIM",
// "Công ty Cổ phần Seedcom Fashion Group",
// "công ty cổ phần thực phẩm Uniben Việt Nam",
// "Công ty cổ phần thương mại dịch vụ Tràng Thi",
// "Công ty CP Bất động sản Du lịch Ninh Vân Bay",
// "Công ty CP Hóa dầu Quân đội",
// "công ty dai-ichi life",
// "công ty Grab",
// "Công ty Hệ thống thông tin FPT",
// "Công ty JLL",
// "công ty manulife",
// "Công Ty MI HỒNG",
// "công ty Nestle",
// "công ty Nhựa Đồng Nai",
// "Công ty Phân phối sản phẩm Viễn thông FPT",
// "công ty prudential",
// "Công ty Sản xuất Hàng tiêu dùng Bình Tân",
// "CÔNG TY TÀI CHÍNH VIỆT NAM THỊNH VƯỢNG",
// "Công ty Talentnet",
// "Công ty Tập đoàn Công nghiệp Trường Hải",
// "Công ty Thương mại Xuất nhập khẩu Thanh Lễ",
// "Công ty TNHH một thành viên Dầu khí thành phố Hồ Chí Minh",
// "Công ty TNHH MTV Dầu khí Thành phố Hồ Chí Minh",
// "Công ty TNHH MTV Dầu khí TP.HCM",
// "Công ty TNHH Sản xuất Hàng tiêu dùng Bình Tiên",
// "Công ty Việt Hà",
// "công ty Vinconnect",
// "cooccoc",
// "coolmate",
// "coolmate Aircool",
// "coolmate AIRism",
// "coolmate Airy Line",
// "coolmate Cool touch",
// "coolmate Coolmax",
// "coolmate Dry-Ex",
// "coolmate Dry-fit",
// "coolmate Sunstop (HighTech Rayon)",
// "coop mart",
// "coopmart",
// "CotecCons",
// "Cowboy Jack s Saloon",
// "Cowboy Jacks",
// "Cowboy Jacks Saloon",
// "Cozy",
// "CRMViet",
// "CrownX",
// "Ct AIA",
// "Ct Bảo Việt",
// "ct dai-ichi life",
// "ct manulife",
// "ct prudential",
// "CTCP Bia và Nước giải khát Việt Hà",
// "CTCP chứng khoán VNDirect",
// "CTCP Đầu tư hạ tầng Việt Hà",
// "CTCP Hóa dầu Quân đội",
// "CTCP Kinh Doanh Và Đầu Tư Việt Hà",
// "CTCP thương mại dịch vụ Tràng Thi",
// "ctg",
// "Cty AIA",
// "Cty Bảo Việt",
// "Cty BVNT",
// "cty dai-ichi life",
// "cty manulife",
// "cty prudential",
// "Cù lao Bà Sang",
// "cửa hàng Phúc Long",
// "cửa hàng xăng dầu",
// "cung đình",
// "CungAnGiaNoiLoiYeuCha",
// "cungdinh",
// "CUNGKUNBAOVEMOITRUONG",
// "cungkunvandongmoingay",
// "CuocChienSieuXu",
// "Cuocsongmuotma",
// "CuocthiGhidau25namhanhtrinh",
// "Cuoianhdi",
// "Cushman & Wakefield",
// "cushmanwakefield",
// "CVH Spring",
// "CycamoreBinhDuong",
// "đa khoa hoàn mỹ",
// "đa khoa tâm anh",
// "Đà Lạt Milk",
// "Dabaco",
// "DacQuyenKhongTienMat",
// "Đại Đoàn Phát",
// "ĐAI hát su",
// "Đại học FPT",
// "Đại Hội Chém Giá",
// "dai kin",
// "DAI-ICHI LIFE",
// "daiichilife",
// "DaiSuThuongHieuTiki",
// "DAITIEC12",
// "daitiecgiaxinh",
// "DaiTiecNamMoi",
// "Dalat milk",
// "Đạm quý A2",
// "Đặng Thị Ngọc Bích ecopark",
// "Đảo Dừa",
// "Đào tạo và phát triển",
// "dasani",
// "ĐẤT RỪNG PHƯƠNG NAM",
// "Dat Xanh Group",
// "Đất xanh miền",
// "Đất xanh miền bắc",
// "DatGojekBatVangRoi",
// "DatRungPhuongNam",
// "dầu nhờn petrolimex",
// "Đầu thu kỹ thuật số DVB - T2",
// "daunanhfami",
// "DauTruongShopee",
// "Dbay Exchange",
// "đề nghị truy tố 3 cha con ông chủ Tân hiệp phát trần quí thanh",
// "đệ nhất",
// "Đệ Nhất Mì Gia",
// "DEAL0D",
// "DealTienToi",
// "DefineCapitaland",
// "DeLasolCapitaland",
// "Delica",
// "Denam Café",
// "denhat",
// "ĐếntrườngcùngVNPAYQR",
// "DEX Investing",
// "dexinvesting",
// "ĐH FPT",
// "ĐH Greenwich Việt Nam",
// "Địa ốc Phú Long",
// "Địa ốc Sông Tiên",
// "DiabetCare",
// "DIAMOND ALNATA",
// "DIAMOND ALNATA PLUS",
// "DIAMOND BRILLIANT",
// "DIAMOND CENTERY",
// "DIAMONDALNATA",
// "DIAMONDBRILLIANT",
// "DIAMONDCENTERY",
// "dịch vụ Cloud Server",
// "Dịch vụ di động Viettel",
// "Dịch vụ FPT",
// "dịch vụ vận tải petrolimex",
// "dịch vụ VinDS",
// "dịch vụ xăng dầu petrolimex",
// "Dielac Grow Plus",
// "Dielac Grow Plus Tổ Yến",
// "Điện cơ Thống Nhất",
// "Điện mặt trời Hồng Liêm 3",
// "Điện máy chợ lớn",
// "điện máy xanh",
// "điện quang",
// "dienmaycholon.com",
// "dienmayxanh",
// "dienmayxanh.com",
// "điều hòa",
// "điều hòa pana",
// "điều hòa panasonic",
// "dieunhobevidai",
// "Digital",
// "Dim Tu Tac",
// "DiMoCungThayQRMoMo",
// "Dimtutac",
// "dmcl",
// "ĐMCL",
// "dmx",
// "đmx",
// "dnp",
// "DNP Corp",
// "Dnp holding",
// "DNP Water",
// "Đỗ Quang Hiển",
// "Đỗ Quang Vinh",
// "Đó Theatre",
// "Đô thị Du lịch Cần Giờ",
// "đô thị lấn biển Cần Giờ",
// "Đô thị mới Trũng Kênh",
// "Đô thị Trũng Kênh",
// "Đỗ Vinh Quang",
// "DOAN NGUYEN HOUSE",
// "Đổi Bóng - Sáng Đèn",
// "Đổi Bóng Sáng Đèn",
// "Đổi Bóng-Sáng Đèn",
// "DOJI",
// "Dojiwatch",
// "Dojji",
// "Dolpansam",
// "dooki",
// "Dookki",
// "DoriDoribyTiki",
// "double wing",
// "double wing điện quang",
// "doublewing",
// "doublewing điện quang",
// "Downlight",
// "Downlight điện quang",
// "Downlight rạng đông",
// "Downlight TLC",
// "downy",
// "dr ruoi",
// "dr.thanh",
// "Dragon Capital",
// "Dragon Cappital",
// "Dragoncapital",
// "DragonX",
// "Dream game",
// "Dream Games",
// "Dream kid",
// "Dream kids",
// "Dreamgame",
// "Dreamgames",
// "dropi",
// "droppi",
// "droppii",
// "droupii",
// "DRPN",
// "drwin",
// "Dự án Cần Giờ",
// "Dự án Casa del rio",
// "Dự án IFC ONE",
// "Dự án Lấn Biển Cần giờ",
// "dự án Ngô Mây",
// "Dự án Nhà máy điện gió Hòa Đông 2",
// "Dự án Nhà máy điện gió Lạc Hoà 2",
// "dự án thủ thiêm",
// "Dự án Trũng Kênh",
// "Dự án trung tâm điện khí LNG Hải Lăng",
// "dự án Vega",
// "Dự án Vĩnh Long",
// "đưa bột sữa nguyên liệu giá thấp vào sản xuất, Vinamilk",
// "DuaLipa",
// "Đức Việt",
// "ĐủMónBạnMê",
// "DungBoBua",
// "DuocAnCaNgaMoMoLo",
// "Dương THACO",
// "Dương Trường Hải",
// "đường vinamilk",
// "Dutch Lady",
// "DutchLady",
// "DXG",
// "Dynasty House",
// "DynastyHouse",
// "e mart",
// "e-mart",
// "Ecopark",
// "Electrolux",
// "Elise",
// "Elise VN",
// "emart sala",
// "EMERALD PRECINCT",
// "Employee Engagement",
// "Enfa",
// "Enfa A+ Provital",
// "Enfa kid",
// "EnfaA2",
// "enfaGrow",
// "Enfagrow A+",
// "Enfagrow Premium",
// "Enfagrow Premium Toddler",
// "EnfagrowA2",
// "EnfaMama",
// "Enfamama A+",
// "enfamil",
// "Enfamil A+",
// "Enfamil A+ Lactofree",
// "Enfamil Enspire",
// "EnplusDiamond",
// "EnPlusGold",
// "EnrichingLives",
// "Ensure",
// "ensuregold",
// "ETC",
// "Evergreen",
// "everywherewithyou",
// "F u t a",
// "F88",
// "fa mi",
// "FABET",
// "Facebook Watch",
// "Fagor",
// "fami",
// "FamiCanxi",
// "FamiNguyenChat",
// "famisuadua",
// "Famna",
// "FB watch",
// "FCV",
// "FE",
// "fe credit",
// "Fecredit",
// "Feng Huang",
// "FengHuang",
// "FICO",
// "First Premium",
// "FirstPremium",
// "FIVESEASON HOMES",
// "Flagship Starbuck",
// "FLAMINGO",
// "Flamingo Cat Ba",
// "Flamingo Cát Bà",
// "Flamingo Dai Lai",
// "Flamingo Đại Lải",
// "Flamingo Group",
// "Flamingo Holding",
// "flashsale1k",
// "FLC Ha Long",
// "FLC Hạ Long",
// "FLC Halong",
// "Floordi",
// "fmc",
// "Fohepta",
// "Fontana",
// "Fonterra",
// "FOODFEST30",
// "Foton",
// "FPT AI",
// "FPT Arena",
// "FPT Camera",
// "FPT Capital",
// "FPT Cloud",
// "FPT Digital",
// "FPT Edu",
// "FPT Education",
// "FPT Foxpay",
// "FPT Greenwich",
// "FPT Group",
// "FPT HO",
// "FPT Information System",
// "FPT Investment",
// "FPT IS",
// "FPT Long Châu",
// "FPT Pharmacy",
// "FPT PLAY",
// "FPT Play Box",
// "FPT Polytechnic",
// "FPT Retail",
// "FPT Securities",
// "FPT SHOP",
// "FPT Skillking",
// "FPT Smart Cloud",
// "FPT Software",
// "FPT Telecom",
// "FPT Trading",
// "FPT TV",
// "FPT University",
// "FPT-Sendo",
// "FPTPlayBox",
// "FPTS",
// "Fridge",
// "Friesland Campina",
// "Friso",
// "FrisoPrestige",
// "Fristi",
// "Fu Ta",
// "Fundiin",
// "FUNiX University",
// "FUTA",
// "FUTA Bus Lines",
// "futabus.vn",
// "futabusline",
// "Fuzetea",
// "FV",
// "FWD Việt Nam",
// "FxMills",
// "FxMills VN",
// "fxmillsvn",
// "G-smile",
// "gạch ngói cmc",
// "gạch ốp át cmc",
// "gạch ốp lát cmc",
// "gạch trang trí cmc",
// "GALAXY Play",
// "Game Zon",
// "Game Zone",
// "Gamezon",
// "GameZone",
// "Gamuda",
// "Gamuda Việt Nam",
// "GamudaCentral",
// "GamudaCity",
// "GamudaGardens",
// "GamudaLand",
// "GamudaLandVietNam",
// "GamudaLark",
// "Garden 79CT",
// "Garden 79S",
// "GARDENGATE",
// "gas petrolimex",
// "Gerber",
// "GHN",
// "GHN_phốt",
// "GHN10nam",
// "ghnancap",
// "ghnexpress",
// "GHNHCM",
// "ghnhn",
// "ghnlàmănthiếutráchnhiệm",
// "GHNlamhuhonghang",
// "ghnlừađảo",
// "ghnrutruot",
// "ghntraohang",
// "ghnvotrachnhiem",
// "GHTK",
// "GiaDinhNestle",
// "Giải Đua Xe Mô Tô Việt Nam",
// "Giải Merri",
// "GiamNhuaSongXanh",
// "Giáo dục FPT",
// "Giao hàng tiết kiệm",
// "giao hàng tk",
// "Giao_hàng_nhanh_gian_lận",
// "giao_hàng_viettel",
// "giaohangjt",
// "giaohangnhanhantrom",
// "giaohangnhanhgianlan",
// "giaohangtietkiem",
// "Giày Hạnh Dung",
// "Giấy Vina Kraft",
// "giayhongthanh",
// "GioithieuMoMo",
// "Giovani",
// "Global city",
// "Globalcity",
// "globalk",
// "Globalk",
// "glucena",
// "Gluvita",
// "GO",
// "GO Bình Dương",
// "GO Củ Chi",
// "GO Điện Bàn",
// "go fast",
// "go food",
// "GO Hòa Thành",
// "GO Hồng Ngự",
// "go jek",
// "GO Market Nguyễn Xiển",
// "gỗ Minh Long",
// "GO Nhơn Trạch",
// "GO Phong Nhị",
// "GO Phú mỹ",
// "GO Quảng Nam",
// "go ride",
// "go send",
// "GO Tam kỳ",
// "GO Tân Uyên",
// "GO Thanh Bình",
// "go-food",
// "GO!",
// "goancuong",
// "Goatlac",
// "Gocarprotect",
// "gofast",
// "GoFood",
// "GoFood11K",
// "GoFoodĐê",
// "Gogi house",
// "gogi steak",
// "gogi steak house",
// "GOgialuonluonrehon",
// "Gói cước FPT",
// "gojek",
// "gojek31k",
// "Gojek8K",
// "Gojekchaobanmoi",
// "GojekMoMo",
// "gojekvietnam",
// "gojekvn",
// "Golden Bay",
// "Golden Gate Restaurant Group",
// "GOLDEN MANSION",
// "GoldenBay",
// "GoldenBay602",
// "goldengate",
// "Goldsoy",
// "goldsoy vinamilk",
// "Goldsun Food",
// "GOLF PARK",
// "GOMall",
// "Gong cha",
// "GongCha",
// "Goo.N Vietnam",
// "Goo.NVietnam",
// "Goon",
// "Goonvietnam",
// "goride",
// "Gosend",
// "gosenddi",
// "Gotz",
// "Gourmand",
// "GPON",
// "Grab",
// "grab bike",
// "Grab đi tỉnh",
// "grab express",
// "grab food",
// "Grab Holdings",
// "Grab Hour",
// "grab mart",
// "Grab Pay",
// "Grab Share",
// "grab xe ôm",
// "grab xpress",
// "Grab3Sieu",
// "Grab66",
// "Grab77",
// "Grab88",
// "Grab99",
// "grabbike",
// "grabcar",
// "GrabCOOLECTION",
// "GrabCoZaloPay",
// "Grabexpress",
// "grabexpress4h",
// "GrabFood",
// "GrabFood66",
// "GrabFood77",
// "GrabFoodBaoHet",
// "GrabFoodTroiMua",
// "grabfoof",
// "GrabFromHome",
// "GrabHour",
// "GrabMart",
// "GrabPay",
// "GrabShare",
// "grabxpress",
// "GrabxTinder",
// "Gran melia Nha Trang",
// "Gran Meliá Nha Trang",
// "Grand Bay Ha Long",
// "Grand Bay Halong Villas",
// "Grand Center Quy Nhơn",
// "Grand Park",
// "Grand Sapphire",
// "Grand World",
// "green star sky garden",
// "Grow Plus",
// "growplus",
// "Gsmile",
// "Guardian",
// "gui gui",
// "guigui",
// "Gyu Shige",
// "GyuShige",
// "H&M Vienam",
// "H&M Việt Nam",
// "Ha Long Marina",
// "Hà Nội FC",
// "hadilao",
// "Hadu Sushi",
// "Hadu.Sushi",
// "Hafele",
// "Hải Âu",
// "haidilao",
// "Hamubay",
// "HANH PHUC International Hospital",
// "hanhtrinhthanhxuancungshopeefood",
// "hanhtrinhtronduongbennhau",
// "Hanoi FC",
// "Hanoi Melody Residences",
// "Hao chi",
// "Hảo Hảo",
// "Haochi",
// "haohao",
// "HaoHaoPremium",
// "happy vinamilk",
// "HappyBirthdayLazada",
// "hd bank",
// "HD bank",
// "HD saison",
// "hdsaison",
// "Heinz",
// "HeLienHoanDealLienHoan",
// "Helio",
// "Helios Village",
// "HệMiễnDịchVữngVàng",
// "HePhongThu1170",
// "Heritage",
// "HeSangSanHangSale",
// "HeSinhThaiTaiChinhSo",
// "hey u",
// "HEYU",
// "Hiển lích",
// "Hiển lít",
// "HiFresh",
// "Highland",
// "highlandmomo",
// "Highlands Coffee",
// "highlandscoffee",
// "him lam",
// "Him Lam",
// "Him Lam Chợ Lớn",
// "Him Lam Green Park",
// "Him Lam Hùng Vương",
// "Him Lam Phú An",
// "Him Lam Phú Đông",
// "Him Lam Tân Hưng",
// "Him Lam Thượng Thanh",
// "Him Lam Vạn Phúc",
// "himlam",
// "HK Beer",
// "HNG",
// "Hồ Tràm Complex",
// "Hồ Trọng Vinh",
// "Hồ Việt Hà",
// "Hoá dầu Long Sơn",
// "Hóa dầu long Sơn",
// "hóa dầu petrolimex",
// "Hoa hậu Ngọc Hân",
// "Hoàn Mỹ",
// "hoan my hospital",
// "hoàn mỹ sài gòn",
// "Hoàng Anh Tuấn Inochi",
// "hoàng mai chung",
// "Hoàng Mai Chung",
// "Hoàng Mai Chung CEO",
// "Hoàng Mai Chung chia sẻ cuối tuần",
// "Hoàng Mai Chung chia sẻ hay nhất",
// "Hoàng Mai Chung Chủ tịch",
// "Hoàng Mai Chung Chủ tịch HĐQT",
// "Hoàng Mai Chung Đêm GaLa kỷ niệm 4 năm tại Cần Thơ",
// "Hoàng Mai Chung Doanh nhân",
// "Hoàng Mai Chung đồng hành cùng doanh nhân",
// "Hoàng Mai Chung giao lưu cuối tuần",
// "Hoàng Mai Chung Lãnh đạo",
// "Hoàng Mai Chung Nhà sáng lập",
// "Hoàng Mai Chung sự kiện",
// "Hoàng Mai Chung Talkshow lập nghiệp cùng Team Leader",
// "Hoàng Mai Chung Team building",
// "Hoàng Mai Chung thăm văn phòng",
// "Hoàng Mai Chung tư duy phát triển",
// "Hoàng Mai Chung Vươn ra biển lớn",
// "Hoàng Mai Chung zoom tư duy phát triển",
// "Hoàng Phúc International",
// "HOANG THANH INVESTMENT",
// "HoanTienMax",
// "Hoff",
// "Hoian or",
// "home credit",
// "Home Credit",
// "homedy",
// "Hòn Thơm",
// "Hồng Thạnh",
// "Hongkong land",
// "HopOiMoRa",
// "hot pot story",
// "Hotpot story",
// "hotpotstory",
// "Houze",
// "HR Knowledge",
// "HR news",
// "HR Tech",
// "HR Trends",
// "HRInsiders",
// "HRIS",
// "htn",
// "Huggies",
// "huggiesvietnam",
// "huka",
// "Humana",
// "hưng lộc phát",
// "hưng phát silver sta",
// "Hưng thịnh",
// "Hung Thinh Corp",
// "Hưng Thịnh Corporation",
// "Hưng Thịnh Land",
// "Hunglocvivang",
// "hungthinh",
// "HungThinhCorporation",
// "HungThinhInnovation",
// "Huy Thanh Jewerly",
// "huyện Triệu Phong Quảng Trị",
// "HuyThanhJewerly",
// "icon 40",
// "ICON 56",
// "ICY Chanh Muối",
// "IDP",
// "IFC",
// "IFC Hàm Nghi",
// "ifc one",
// "ifc one saigon",
// "IFC One Tower",
// "IFC Sai Gon One",
// "IFC Saigon One",
// "ifcone",
// "iGate AP2IH",
// "iGate AP2OH",
// "iGate EW12C/CG",
// "iGate EW12S/SG",
// "iGate EW12ST",
// "iGate EW12SX",
// "iGate EW30SX",
// "iGate1",
// "iGate1IH",
// "ILO",
// "inhomes Đại An",
// "inochi",
// "Instagram Reels",
// "InstagramReels",
// "InterContinental + Ha long",
// "InterContinental + Phu Quoc",
// "intercontinental halong",
// "InterContinental Phu Quoc",
// "InterContinental PhuQuoc Long Beach Resort",
// "InterContinental Residences Halong Bay",
// "Internet FPT",
// "IQIYI",
// "itstartsonTikTok",
// "IVAN",
// "Iveco Daily",
// "Ivy Moda",
// "Iwin",
// "Izakaya Ten",
// "j txpress",
// "J&T",
// "J&Texpress",
// "Jack Nguyen",
// "jackpot",
// "jandtxpress",
// "Jewerly Huy Thanh",
// "Jio",
// "Jio Health",
// "Jiohealth",
// "JNT",
// "jntexpress",
// "JnTExpressVietnam",
// "Jtexpress",
// "Jtexpressvn",
// "Jtxpress",
// "Juno",
// "JVC",
// "jvc dnp",
// "jvc tasco",
// "JVC thua lỗ",
// "k-pub",
// "K+",
// "Katinat",
// "KCN Cát Trinh",
// "KDC Bắc Hà Thanh",
// "KDC Bờ Bắc",
// "KDI holdings",
// "KDIHoldings",
// "Kem Cao cấp Twin Cows",
// "Kem dừa - Kem Côn Đảo Dừa Đất",
// "kem hộp Vinamilk",
// "Kem Twin Cows",
// "Kem Vinamilk",
// "Kem Vinamilk Twincows",
// "Kem Yolo Delight",
// "kemkitkat",
// "kemmilo",
// "KemNestle",
// "KemTHTrueMilk",
// "kenko",
// "Keppel",
// "Keppel Land",
// "KeppelLand",
// "KeppelLandVietnam",
// "kết quả xổ số khánh hòa",
// "KFC",
// "Khang An Foods",
// "Khang Dien",
// "Khang Điền",
// "khánh hòa",
// "khi xăng dầu ngoại quan vân phong",
// "kho xăng dầu ngoại quan vân phong",
// "KHÔNG GIAN TRUNG NGUYÊN LEGEND",
// "Khu căn hộ khách sạn BMC Quy Nhơn",
// "Khu chức năng đô thị Trũng Kênh",
// "Khu Công Nghiệp Cát Trinh",
// "Khu cư dân Hưng Thịnh",
// "Khu dân cư Bắc Hà Thanh",
// "Khu dân cư Bờ Bắc",
// "KHU DÂN CƯ LÀNG NGHỀ VÀ TRUNG TÂM XÃ HÀM NINH",
// "Khu dân cư Phước Thọ 1",
// "Khu dịch vụ - du lịch Gio Hải Quảng Trị",
// "Khu đô thị",
// "Khu du lịch dịch vụ Triệu Vân",
// "Khu nghỉ mát du lịch sinh thái Rạch Vẹm",
// "Khu tiểu thủ công nghiệp Hàm Ninh",
// "khử trùng",
// "KhuiDealKhungGiangSinh",
// "KIA",
// "KIAMORNING",
// "kiến thiết hồ chí minh",
// "kiến thiết TP.HCM",
// "kiến thiết tphcm",
// "KienTaoCuocSongMoi",
// "king",
// "king bbq",
// "King Crown Infinity",
// "King Crown Village Thảo Điền",
// "kingbbq",
// "Kingdom",
// "Kingdom Beer Club",
// "KINGSTON RESIDENCE",
// "Kinh Đô Ánh Sáng",
// "Kinh doanh thương mại Thịnh Phát",
// "Kitchenware",
// "Klara S",
// "KLVSustainability",
// "KLVSustainableUrbanisation",
// "knor",
// "Knorr",
// "Koi",
// "Koi The",
// "Koi Thé",
// "KoiThe",
// "Kosmos",
// "Kplus",
// "Kpluscinema",
// "KplusKIDS",
// "kplussports",
// "kqxs hà nội",
// "kqxs hcm",
// "kqxs hn",
// "kqxs hồ chí mình",
// "kqxs khánh hòa",
// "kqxs sg",
// "kqxs thủ dô",
// "kqxs tphcm",
// "kqxshcm",
// "kqxskh",
// "Kraft Vina",
// "Kredivo",
// "Kubo",
// "KUNDUNGOAN",
// "KUNKHAMPHA",
// "KUNMarathon",
// "KUNSIEUPHAM",
// "KUNVANDONG",
// "Kỳ Co GateWay",
// "la la",
// "la vie",
// "la za da",
// "Lắc Bão Xu",
// "lacbaoxu",
// "LacChanDong",
// "LacDealSanhDieu",
// "Lacoste Vietnam",
// "Lacoste VN",
// "Lactes",
// "lafooco",
// "Lake view",
// "Lake View Quận 2",
// "Lakeview",
// "lala",
// "lala move",
// "Lala2h",
// "LALA4W",
// "lalamove",
// "lalamovevietnam",
// "lalamovevn",
// "LALANEW",
// "LalaTRUCK",
// "LalaTRUCk1000",
// "LalaTRUCk2000",
// "LalaTRUCK500",
// "LalaTRUCKs",
// "lamgilamdungbobua",
// "Lan chi",
// "Lanchi",
// "Land mark",
// "Land mark81",
// "Landmark",
// "Landmark 81",
// "Landmark81",
// "Làng Hà Lan Ecopark",
// "Lẩu Băng Chuyền Osaka",
// "Lẩu nấm Gia Khánh",
// "launamgiakhanh",
// "lauphanbuffet",
// "lavie",
// "Lavita Charm",
// "Lavita Garden",
// "Lavita Thuận An",
// "lazada",
// "Lazada ads",
// "lazadaad",
// "lazadaads",
// "lazadaadsvietnam",
// "Lazadaexpress",
// "LazadaLivestream",
// "LazadaLogistics",
// "LazadaLogisticsVN",
// "LazadaMienPhiGiaoHangMoiNgay",
// "lazadarun",
// "lazadarun2023",
// "LazadaSaleDep",
// "LazadaSuperParty",
// "LazadaSupershow",
// "LazadaTetSupershow",
// "LazadaxHP",
// "LazBeauty",
// "LazBeautyxMONO",
// "LazDep",
// "Lazgame",
// "LazLivePlus",
// "lazmall",
// "LazMallsalechinhhang",
// "LazMallsalegiuathang",
// "LazMallxHyunBin",
// "lazmaster4",
// "lazprentice",
// "LazStyle",
// "Le Gourmet",
// "Lê Khắc Hiệp",
// "Lê Minh Chung",
// "Le Monde Steak",
// "Le Quoc Minh",
// "Leadership",
// "Learning & Development",
// "learnontiktok",
// "led",
// "led điện quang",
// "led rạng đông",
// "led TLC",
// "lemeridiensaigon",
// "LeparcGamuda",
// "LEX",
// "LEXINGTON RESIDENCE",
// "LG",
// "Liên hiệp Hợp tác xã Thương mại TP.HCM",
// "Liên Thành",
// "Lif kun",
// "LifeatCốcCốc",
// "LifeBeyondCompare",
// "Lim Tower III",
// "linkco",
// "LionBrokers",
// "lipovitan",
// "Lipton Milktea",
// "LiptonMilktea",
// "LIVAS",
// "Live Bank",
// "LiveBank",
// "lò hấp",
// "lò hấp panasonic",
// "Lò nướng",
// "lò nướng pana",
// "lò nướng panasonic",
// "Lò vi sóng",
// "lò vi sóng pana",
// "lò vi sóng panasonic",
// "Lộc Phúc Fine Jewelry",
// "Lộc Phúc vàng",
// "LocPhucFineJewelry",
// "locphucjewelryoffical",
// "Lof Ba Vì",
// "Lof Malto",
// "Lofbavi",
// "lofkun",
// "LofMalto",
// "Logistics ICD Vĩnh Phúc",
// "Long Việt",
// "Longchau",
// "Lookkool",
// "LớpSữaVàngTinhTuý",
// "lotte",
// "Lotte Finance Paylater",
// "Lotte Paylater",
// "LotteMart",
// "Lotus Group",
// "LPL TRADE",
// "lpltrade",
// "LSP",
// "LUCKY DRAGON",
// "LUCKY PALACE",
// "Luoncogocar",
// "LuonCoGoRide",
// "Lương Xuân Hà ecopark",
// "Luontoasang",
// "Ly starbuck",
// "Ly Tu Trong College",
// "lzd",
// "Lzd express",
// "lzdads",
// "lzdmallads",
// "m-150",
// "m150",
// "Mã CVT",
// "mã HUT",
// "Mã JVC",
// "ma san",
// "mã tpp",
// "Macro",
// "Macro Equities",
// "macroequities",
// "MadamNu",
// "Maggi",
// "Mai Hương Nội",
// "Mai Kiều Liên",
// "Malibu Hội An",
// "Malloca",
// "Maloca",
// "Manclub",
// "Mạng 4 chữ",
// "Mạng 5 chữ",
// "Mạng FPT",
// "Mạng internet Viettel",
// "Mạng internet VNPT",
// "Mango Stores Vietnam",
// "Mango Vietnam",
// "Mango VN",
// "Manpower",
// "ManpowerGroupVietNam",
// "ManpowerVietNam",
// "MANULIFE",
// "manulife bảo hiểm",
// "manulife bh",
// "Marina Bayfront District Hạ Long",
// "Marina Bayfront Terrace Hạ Long",
// "Marina Bayfront Towers Hạ Long",
// "Maritime bank",
// "maritimebank",
// "Masan Group",
// "Masan high tech",
// "MasanGroup",
// "massan",
// "Massan",
// "Masteri An phú",
// "mastericenterpoint",
// "mastericentral",
// "Masteries",
// "MasteriLumiere",
// "MasteriLumiereRiverside",
// "MasteriParkLand",
// "Masterise",
// "masterise group",
// "masterise home",
// "masterise homes",
// "masterise thảo điền",
// "masterisecentral",
// "masterisecentralpoint",
// "masterisecentre",
// "masterisecentrepoint",
// "masterisegroup",
// "masterisehome",
// "MasteriseHomes",
// "MasteriseLumiere",
// "MasteriseLumiereRiverside",
// "MasteriseParkLand",
// "masterisequận9",
// "mẫu giáo ILA",
// "Max 3D",
// "Max 4D",
// "Max3DPro",
// "Máy chế biến thực phẩm",
// "Máy chế biến thực phẩm panasonic",
// "Máy diệt khuẩn panasonic",
// "Máy ép",
// "máy ép pana",
// "máy ép panasonic",
// "máy giặt",
// "máy giặt pana",
// "máy giặt panasonic",
// "máy hút bụi panasonic",
// "Máy làm bánh mì",
// "máy làm bánh mì pana",
// "máy làm bánh mì panasonic",
// "máy lạnh",
// "máy lạnh LG",
// "máy lạnh pana",
// "máy lạnh panasonic",
// "máy lạnh Toshiba",
// "máy lọc không khí Daikin",
// "máy lọc không khí Samsung",
// "máy lọc không khí Sharp",
// "máy lọc không khí Xiaomi",
// "máy lọc kk Daikin",
// "máy lọc kk Samsung",
// "máy lọc kk Sharp",
// "máy lọc kk Xiaomi",
// "máy lọc nước panasonic",
// "máy nước nóng panasonic",
// "máy sấy panasonic",
// "Máy xay",
// "máy xay pana",
// "máy xay panasonic",
// "Mazda 2",
// "Mazda 3",
// "Mazda 6",
// "MB Bank",
// "mb shinsei",
// "mbb",
// "MBBank",
// "MBS",
// "Mc Donalds",
// "mcredit",
// "Mead Johnson",
// "Meadow 85S",
// "Meadow 89CT",
// "meat & meat",
// "Meat and Meet",
// "Meat life",
// "Meat Plus",
// "meat+",
// "Meatdeli",
// "Meatlife",
// "meatplus",
// "Media mart",
// "MediaMart",
// "Meey Ads",
// "Meey CRM",
// "Meey Group",
// "Meey Land",
// "meey map",
// "Meey Page",
// "MeeyAds",
// "meeycoin",
// "MeeyCRM",
// "MeeyGroup",
// "Meeyland",
// "Meeyland Camp Tư duy đột phá",
// "Meeyland câu lạc bộ triệu Meey",
// "Meeyland chia cổ tức",
// "Meeyland chia sẻ cùng người sáng lập",
// "Meeyland Chiến binh",
// "Meeyland Chung tay về đích",
// "Meeyland chuyển đổi số bất động sản",
// "Meeyland Chuyển đổi số bđs",
// "Meeyland CLB triệu Mey",
// "Meeyland cổ đông",
// "Meeyland cổ phần",
// "Meeyland Cổ phiếu",
// "Meeyland coin",
// "Meeyland Cộng đồng",
// "Meeyland Công nghệ - Tài chính BĐS",
// "Meeyland Cùng nhau khai thác giá trị",
// "Meeyland Đào tạo",
// "Meeyland đầu tư",
// "Meeyland đóng góp",
// "Meeyland Đồng hành",
// "Meeyland giá Meey sẽ tăng liên tục",
// "Meeyland Giá trị Mey",
// "Meeyland gói góp",
// "Meeyland gọi vốn",
// "Meeyland gọi vốn cộng đổng",
// "Meeyland Gom Mey",
// "Meeyland Góp gói đồng hành",
// "Meeyland Góp gói phát triển Hệ sinh thái Công nghệ Tài Chính BDS",
// "Meeyland góp tiền",
// "Meeyland góp tiền mua cổ phần",
// "Meeyland góp vốn",
// "Meeyland Hướng tới IPO",
// "Meeyland huy động vốn",
// "Meeyland IPO",
// "Meeyland IPO 2025",
// "Meeyland Khát vọng chiến binh",
// "Meeyland Kỳ lân",
// "Meeyland Làm giàu",
// "Meeyland Lên sàn IPO",
// "Meeyland Meeyer",
// "Meeyland Mey tăng giá",
// "Meeyland Mey trước IPO",
// "Meeyland nghìn tỷ",
// "Meeyland nguồn vốn",
// "Meeyland Nhà đầu tư",
// "Meeyland nhà đầu tư lựa chọn",
// "Meeyland quỹ đầu tư",
// "Meeyland rót vốn",
// "Meeyland Sàn giao dịch bất động sản công nghệ 4.0",
// "Meeyland sở hữu",
// "Meeyland Thủ lĩnh",
// "Meeyland Thưởng quảng cáo",
// "Meeyland tích luỹ",
// "Meeyland triệu đô",
// "Meeyland triệu MEY",
// "Meeyland trở thành cổ đông",
// "Meeyland Tư duy đột phá",
// "Meeyland Văn phòng đại diện",
// "Meeyland vốn hoá",
// "Meeyland vốn lưu động",
// "Meeyland Vua của ngành bất động sản",
// "Meeyland Vươn xa biển lớn",
// "meeymap",
// "MeeyPage",
// "mega",
// "Mega Mall Times City",
// "Mega market",
// "MegaMarket",
// "Meiwei",
// "Melody Residences",
// "Meries",
// "Merrie",
// "Merries",
// "Merritrade",
// "Mẹsiêuphàm",
// "Metro",
// "mey",
// "Meyhomes",
// "Meyhomes Phu Quoc",
// "mht",
// "Mì cung đình",
// "Mì Kokomi",
// "Mì Omachi",
// "Mì Sagami",
// "Mì3Miền",
// "micungdinh",
// "MikhoaitâyCungĐình",
// "Millennium",
// "Milo",
// "Milovietnam",
// "Minh Tuấn - Sông Ray",
// "MinhCoDoiBanCoDeal",
// "MINI",
// "Mini bus",
// "MINI Convertible S Convertible",
// "MINI Cooper S 3 Doors",
// "MINI Cooper S 5 Door",
// "MINI Countryman",
// "Mini go",
// "MINI John Cooper",
// "MINI John Cooper Work 3 Door",
// "MINI John Cooper Works",
// "MINI John Cooper Works Clubman",
// "MINI John Cooper Works Convertible",
// "MINI John Cooper Works Countryman",
// "MINI One",
// "MINI One 5 Door",
// "MINI One 5-Cửa",
// "Minigo",
// "MIPEC",
// "mirae asset",
// "Mitsubishi Fuso",
// "Mixue",
// "Mixxi",
// "Mixxo",
// "Mizuki",
// "Mizuki Park",
// "MizukiPark",
// "mm mega",
// "MMPC",
// "Mo Mo",
// "Mobihome",
// "MobileMoney",
// "moca",
// "MoGrabDungMoca",
// "MoLazada",
// "MoMo",
// "momoapp",
// "MoMoBAEMIN",
// "MoMoGoal",
// "MoMoPhaChe",
// "momoquyengop",
// "MoMoxCoffeerary",
// "Mon Blance",
// "Moo beef",
// "Moo Beefsteak",
// "Moony",
// "Morning",
// "Morning/New Morning",
// "MORNING12",
// "moshopeedungshopeepay",
// "MotCamGiacRatYomost",
// "MotSachTiki",
// "MSB",
// "MSB Bank",
// "MU9",
// "MuacangnhieuTrungcangto",
// "MuaDealYeuThuong",
// "muasalebangHOCHIMINH",
// "muasamcoloi",
// "Muay Thai",
// "mũi né summerland",
// "MuonShopeeFoodToTinh",
// "Muya Thai",
// "MWG",
// "Mỹ Tường Viên",
// "myK",
// "MySign",
// "mytuongvien",
// "MyTV",
// "MyTV VNPT",
// "MyViettel",
// "MyVNPT",
// "Nam Dương",
// "NAM LONG GROUP",
// "Nam Ngư",
// "Nam Phú Quốc",
// "Nam Sài Gòn",
// "Nan Optipro",
// "NAN Organic",
// "Nan Supreme",
// "NANOptipro4",
// "NANOPTIPROKid",
// "NANSupremePro3",
// "Napnangluonggiutraidatxanh",
// "Navigos Việt Nam",
// "NavigosSearch",
// "NBET",
// "ncg",
// "Nem Fashion",
// "NEM NEW",
// "Neotrades",
// "Nestle",
// "Nestlé",
// "Nestle Nan",
// "Nestlé Nan Infinipro A2",
// "Nestlé Nan Organic 3",
// "Nestlé Nan Supreme 3",
// "Nestle Yogu",
// "nestlemilo",
// "NestleNutrition",
// "NestlePtit",
// "Nestlevietnam",
// "Net FPT",
// "Nét Huế",
// "Netflix",
// "New Sphinx Beer Bar",
// "New World PhuQuoc Resort",
// "Ngân hàng Á Châu",
// "Ngân Hàng Á Châu",
// "ngân hàng acb",
// "ngân hàng công thương",
// "ngân hàng Đầu tư và Phát triển Việt Nam",
// "Ngân Hàng Hàng Hải",
// "ngân hàng kỹ thương",
// "Ngân hàng MB",
// "Ngân hàng MSB",
// "ngân hàng ngoại thương",
// "Ngân hàng nông nghiệp",
// "ngân hàng phương đông",
// "Ngân hàng Quân Đội",
// "Ngân hàng Sài Gòn - Hà Nội",
// "Ngân hàng SHB",
// "Ngân hàng thương mại cổ phần công thương",
// "Ngân Hàng tiên phong",
// "NGÂN HÀNG VIỆT NAM THỊNH VƯỢNG",
// "ngân hàng vietcombank",
// "NgànDealThầnChưởng",
// "nghỉ dưỡng alma",
// "nghỉ dưỡng phú long",
// "NghienLazMall",
// "NghienShopee",
// "ngk vinamilk",
// "Ngô Đức Vũ",
// "Ngô Thành Chung",
// "Ngọc Trai",
// "ngói CMC",
// "NgoimatGrabgiao",
// "NgonNhưPhởQuán",
// "ngưu phồn",
// "Nguyễn Danh Hiếu",
// "nguyễn duy hưng",
// "Nguyễn Hải Ninh",
// "Nguyễn Hồ Nam",
// "Nguyễn Hoàng Tuấn",
// "Nguyễn Jack Nhựt Minh",
// "Nguyễn kim",
// "Nguyễn Kim",
// "Nguyễn Thế Minh",
// "Nguyen Thi Thanh Huong",
// "nguyễn thị trà my",
// "Nguyễn Văn Hiếu",
// "Nhà hát Đó",
// "Nhà máy điện mặt trời Phước Ninh",
// "Nhà máy điện rác Xuân Sơn",
// "Nhà máy nước DNP Quảng Bình",
// "Nhà máy nước Nhị Thành",
// "Nhà máy nước sạc NS3",
// "Nhà máy nước sạch Bắc Giang",
// "Nhà thuốc An Khang",
// "nhà thuốc Guardian",
// "nhà thuốc Jio health",
// "nhà thuốc L.C",
// "Nhà thuốc Long Châu",
// "nhà thuốc pharma",
// "Nhà thuốc Trung Sơn",
// "nhà thuốc watsons",
// "Nha Trang",
// "Nhân sự",
// "Nhân sushi",
// "nhancuoihuythanh",
// "NhanhTienChinhXac",
// "nhật vượng",
// "nhiên liệu bay petrolimex",
// "Nhơn Hội New City",
// "nhựa Bình Minh",
// "Nhựa Đồng Nai",
// "nhựa đường petrolimex",
// "Nhựa Duy Tân",
// "NhungDoaHoaKienCuong",
// "NIC",
// "Night Wolf - Sâm Ngọc Linh Kon Tum K5",
// "Nike Viet Nam",
// "Nike Vietnam",
// "Nike VN",
// "Ninh Vân Bay",
// "Ninomaxx",
// "Ninomaxx Concept",
// "NK",
// "Nồi cơm điện",
// "nồi cơm panasonic",
// "Nội Thất Hafele",
// "nội thất hansem",
// "nội thất HPL",
// "nội thất Thanh Thùy",
// "nội thất Yên Lâm",
// "NoSayGames",
// "Nova",
// "Nova College",
// "nova consumer",
// "Nova Group",
// "nova land",
// "NovaCollege",
// "NovaConsumer",
// "Novagroup",
// "NovaHillsMuiNe",
// "NovaLand",
// "NovalandGroup",
// "novaworld",
// "novaworldbinhchau",
// "novaworldphanthiet",
// "NowdoitenthanhShopeeFood",
// "NowShopeeFood1808",
// "Nowvn",
// "NSC",
// "NT Long Châu",
// "Nữ trang Mi Hồng",
// "NUAGIA",
// "Núi Pháo",
// "Number 1 Active Chanh Muối",
// "Number 1 Chanh & Dâu",
// "Number1ActiveChanhMuối",
// "Number1Chanh&Dâu",
// "Nước ép Vfresh",
// "nước gạo TH",
// "nước giải khát vinamilk",
// "nước giải khát vnm",
// "nước mắm 584",
// "nước mắm 584 nha trang",
// "Nước tăng lực ABBEN",
// "Nước tăng lực Hổ Vằn",
// "Nước tăng lực M-150",
// "Nước Tăng Lực Monster",
// "Nước tăng Lực Number 1",
// "Nước tăng lực PhinDeli",
// "Nước Tăng Lực Ready",
// "Nước tăng lực rồng đỏ",
// "Nước tăng lực Samurai",
// "Nước tăng lực sting",
// "Nước Tăng Lực Wake Up 247",
// "nước trái cây TH",
// "nước trái cây Vfresh",
// "nước uống năng lượng my joy",
// "nước uống năng lượng power",
// "Nướcmắm584NhaTrang",
// "nuocmamlienthanh",
// "NướctăngLựcNumber1",
// "Nuti",
// "Nuti IQ",
// "Nuti IQ Gold",
// "nutifood",
// "NutifoodGrowPLUS",
// "NutiFoodThuyDien",
// "Nutifoodvietnam",
// "nutimilk",
// "Nutizen",
// "Nutren Junior",
// "Nuvi Grow",
// "Nuvi jelly",
// "Nuvi rau củ",
// "Nuvi sữa chua lên men",
// "Nuvi Sữa lắc trái cây",
// "Nuvi sữa lúa mạch",
// "NuviGrow",
// "NuviPower",
// "Nuvita Grow",
// "Ô long Tea+",
// "O mờ",
// "Ô tô Trường Hải",
// "ocean park",
// "Ocean Park 2",
// "Ocean Park 3",
// "OCP 3",
// "Oggi",
// "OggiGold",
// "OH",
// "Oishi Tea Go",
// "OishiTeaGo",
// "OiZi",
// "olong plus",
// "olong tea plus",
// "olongplus",
// "ÔlongTea+",
// "OM Distribution",
// "OM Real Estate",
// "OMD",
// "OMG",
// "omo",
// "OMRE",
// "One Housing",
// "One Mount",
// "OneHousin",
// "OneHousing",
// "OneMount",
// "oneSME",
// "ống nhựa đồng nai",
// "onlinecrm",
// "op tran",
// "op tran điện quang",
// "op tran rạng đông",
// "op tran TLC",
// "Opal",
// "ORCHARD GARDEN",
// "ORCHARD PARKVIEW",
// "Organic",
// "Orient Oil",
// "OSAKA.1",
// "OSAKA.O",
// "Ovaltine",
// "PA",
// "pa na so nic",
// "palasolic",
// "palasonic",
// "Pampers",
// "Pampersvietnam",
// "Pampervietnam",
// "pan",
// "Pana",
// "pana sonic",
// "panasolic",
// "Panasonic",
// "Panasonic 2024",
// "panasonich",
// "panasonick",
// "panasonik",
// "pangroup",
// "panna",
// "pannasonish",
// "park city",
// "park hill",
// "Park Hyatt Phu Quoc Residences",
// "parkcity",
// "Passion For Better Vietnam",
// "PassionForBetterVietnam",
// "pavilion",
// "PayAllinZalo",
// "PDR",
// "Pedia Plus",
// "Pediaplus",
// "PediaSure",
// "PediasureVietnam",
// "PERKYLiON",
// "PERSOLKELLY",
// "Petro limex",
// "Petro Times",
// "Petrolimec",
// "Petrolimex",
// "petrolimex lào",
// "petrolimex sing",
// "petrolimex singapore",
// "PetroTimes",
// "PG Tanker",
// "PGAS",
// "PGCC",
// "PGT",
// "pha ma city",
// "Phachoitrungthat",
// "phạm nhật vũ",
// "Phạm Thành Thái Lĩnh",
// "Phạm Thu Hương",
// "Phạm Thúy Hằng",
// "Phạm Văn Thanh",
// "Phan Anh Tuấn Inochi",
// "Phân khu Ánh Dương",
// "Phân khu Đảo Ngọc",
// "Phân khu Hải Đăng",
// "Phân khu Phố Biển",
// "Phân khu sakura",
// "Phân khu Thời Đại",
// "Phân khu Vịnh Tây",
// "Phân khu Vịnh Thiên Đường",
// "Phân khu Vịnh Xanh",
// "Phan Thị Thu Thảo",
// "Phan Thùy Giang",
// "PhaoDealLienHoan",
// "phar ma",
// "pharma city",
// "pharmacity",
// "Pharmacy",
// "Phát đạt",
// "Phát Đạt Bàu Cả",
// "PHAT DAT GROUP",
// "Phát Đạt Quy Nhơn",
// "PhatDat",
// "phở 24",
// "Phở cung đình",
// "phổ đình",
// "phô mai tươi milk tiger",
// "phô mai tươi zott",
// "phô mai tươi zott milk tiger",
// "Phô mai Vinamilk",
// "Phô mai Vinamilk Susu",
// "phô mai vnm",
// "phở thìn",
// "phocungdinh",
// "PhởĐệNhất",
// "Phoenix Mountain",
// "Phòng khám chẩn đoán hình ảnh việt nhật",
// "Phòng khám Đa Khoa Việt Nhật",
// "phòng khám hoàn mỹ",
// "Phòng khám Quốc tế Hạnh Phúc",
// "photbestexpress",
// "phốtghn",
// "photghtk",
// "phốtVNPost",
// "phú cường",
// "phú điền",
// "phú điền Group",
// "PHÚ LONG GROUP",
// "Phu My Hung",
// "Phú Mỹ Hưng",
// "phuc long",
// "Phúc Long Coffee & Tea",
// "Phúc Long Cộng Hòa",
// "Phúc Long Gò Vấp",
// "Phúc Long Kiosk",
// "Phuc Long tea",
// "Phương Trang",
// "PhuongTrang",
// "phuongtrangbus",
// "pin VinES",
// "Pizza 4P",
// "Pizza 4Ps",
// "Pjico",
// "Pk Hạnh Phúc",
// "Pk Quốc tế Hạnh Phúc",
// "pl",
// "Plastchem",
// "PLC",
// "PLX",
// "Pocari Sweat",
// "PolyKBeauty",
// "Powerbowl",
// "PPT",
// "Predator Energy Drink",
// "Pregestimil",
// "Premier Village Ha Long Bay Resort",
// "premium",
// "Prime Group",
// "PrimeGroup",
// "Primus",
// "Probidekhangmanhme",
// "propzy",
// "Provital",
// "PRUDENTIAL",
// "prudential bảo hiểm",
// "prudential bh",
// "PT Fu Ta",
// "PTC",
// "PTS",
// "PV OIL",
// "PVOil",
// "PVOILEasy",
// "PVOILNews",
// "PVOILRadio",
// "qctiki",
// "Qmart",
// "QNS",
// "qr san kim cuong",
// "qrnhantienmomo",
// "qrsankimcuong",
// "qrsanvang",
// "QRThanhToanMoMo",
// "quán ăn ngon",
// "Quang Masan",
// "QuangcaoCocCoc",
// "quanngonquanminh",
// "Queen land",
// "Queenland",
// "quốc tế hoàn mỹ",
// "quốc tế mỹ",
// "Quỹ Đầu tư Cân bằng Tuệ Sáng",
// "Quỹ Đầu tư Cân bằng Tuệ Sáng",
// "Quỹ Đầu tư Cổ phiếu Tập trung Cổ tức",
// "Quỹ Đầu Tư Cổ Phiếu Việt Nam",
// "rạng đông",
// "Rau má mĩ",
// "rau má mix",
// "RauMa Mix",
// "Raumamix",
// "realestate",
// "Recruitment",
// "red bull",
// "redbull",
// "Redsun",
// "Ree-pay",
// "RegentPhuQuoc",
// "remaps",
// "Rever",
// "ReviewMuaYeuThuong",
// "revive",
// "Revive Salted Lemon",
// "rì vai",
// "Rikvip",
// "Riso Gold",
// "Riso Opti Gold",
// "River Panorama",
// "RIVERGATE",
// "Riverview 440 Vĩnh Hưng",
// "RMM",
// "Rock Energy",
// "Rockstar",
// "Rondo",
// "rongranlendeal",
// "royal city",
// "ruby",
// "RUBY PRECINCT",
// "sacom bank",
// "Sacombank",
// "sài thành",
// "Saigon Co-op",
// "Saigon One Tower",
// "Saigon Petro",
// "Saigon sunbay",
// "Sailing Club + Ha Long",
// "sailing club halong",
// "Sailing Club Phu Quoc",
// "Sailing Club Residences Ha Long",
// "Sailing Club Signature Residences Ha Long Bay",
// "Sailing Club Signature Resort Phu Quoc",
// "sailingclubresidenceshalongbay",
// "Sala",
// "Samsung",
// "San Fu Lou",
// "Sân golf Tân Sơn Nhất",
// "San Hô",
// "sàn ibmex",
// "Sản phẩm số FPT",
// "Sân Vận động Hàng Đẫy",
// "Sanfulou",
// "SANG0D",
// "sanmacroequities",
// "SANQUAKUN",
// "Sao Biển",
// "sao ta",
// "SaoBomTan",
// "saophaixoan",
// "saphire",
// "sapphire",
// "Sapphire 1",
// "Sapphire 2",
// "Sapphire 3",
// "Sapphire 4",
// "sapuwa",
// "SauGioHocDenGioYo",
// "Savico",
// "savico auto mall",
// "Savico Tower",
// "Savills bất động sản",
// "Savills BDS",
// "Savills cho thuê văn phòng",
// "Savills nghỉ dưỡng",
// "SB",
// "SC Hoff",
// "sc uống betagen",
// "sc vinamilk",
// "sc vnm",
// "SCB",
// "SCG",
// "SCG_Smartboard",
// "SeasonsavenueCapitaland",
// "seasonsevenue",
// "sen đỏ",
// "sendo",
// "Sendo farm",
// "Sendo1212",
// "SendoHoanTien",
// "SendoSaleKhongLo",
// "Senturia Bình Chánh",
// "Senturia Nam Sài Gòn",
// "Seoul Garden",
// "SeoulGarden",
// "sepprogram",
// "Shamoji Robata Yaki",
// "Shangchi Lẩu băng chuyền",
// "Sharp",
// "SHB finance",
// "shbfc",
// "shbfinance",
// "Shein",
// "sherpa",
// "Shiitake",
// "SHIN",
// "Shine Combo",
// "ShineAtHome",
// "Shinhanfiance",
// "shinhanfinance",
// "shopee",
// "Shopee",
// "Shopee Ads",
// "Shopee Ex",
// "shopee xpress",
// "Shopeeads",
// "ShopeeBatTrendGiaSoc",
// "ShopeeExpress",
// "ShopeeFood1010",
// "ShopeeFood1111",
// "ShopeeFood1212",
// "ShopeeFood1402",
// "ShopeeFood1501",
// "ShopeeFood99",
// "ShopeeFoodCheck",
// "ShopeeFoodCheck1402",
// "ShopeeLive",
// "shopeepayvietnam",
// "shopeepayvn",
// "shopeesogiday",
// "Shopeetangtien",
// "ShopeeVietnam",
// "shopeevn",
// "ShopeeXpress",
// "shopepay",
// "Shophouse Nguyễn Cơ Thạch",
// "Shophouse Sala",
// "Shoppe",
// "shoppee",
// "shoppeepaylater",
// "shoppepaylater",
// "Showroom CMC",
// "sì ting",
// "Siam Cement Group",
// "Siêu Sinh Nhật",
// "siêu thị mega",
// "siêu thị metro",
// "SIEUDEAL",
// "SIEUDEAL20",
// "SIEUDEAL20K",
// "SIEUDEAL25",
// "SIEUDEAL25K",
// "SIEUDEAL30",
// "SIEUDEAL30K",
// "SIEUDEAL40",
// "SIEUSALE",
// "sieusalevanmon",
// "SIEUTIEC0D",
// "similac",
// "SimilacVietnam",
// "sinh thái Hồ Xuân Khanh",
// "sinh thái Nhơn Hội",
// "Sinh Thái Vũng Bầu",
// "sinhnhatGO25tuoi",
// "sinhnhatsendo",
// "SInvoice",
// "Six Senses Nha Trang",
// "Six Senses Ninh Van Ba",
// "sjc",
// "skoda",
// "Sky 89",
// "Sky89",
// "Skylar",
// "Slash",
// "Smart City",
// "SmartBox",
// "smartcityvinhomes",
// "Smartone",
// "SMBC",
// "socialcaphouse",
// "Soft",
// "sohocapitaland",
// "SohoHeritageWestLake",
// "Sonatus",
// "songtotcungmomo",
// "SONKIM LAND COPORATE",
// "sọp pi",
// "Soy Secretz",
// "Sparta",
// "Sparta Beer Club",
// "SPaylater",
// "SPFOOD122",
// "SPFOOD5",
// "SPFOOD82",
// "Spice World Hotpot",
// "SPX",
// "Starbuck Vietnam",
// "Starbucks Flagship Store",
// "Starbucks Mooncake Giftbox",
// "Starbucks Refreshers",
// "Starbucks Rewards",
// "Starbucks Việt Nam",
// "Starbucks Vietnam",
// "STB",
// "sting",
// "sting world",
// "stradex",
// "sữa Anlene",
// "sữa Anmum",
// "Sữa bột Vinamilk",
// "Sữa bột Vinamilk Dinh Dưỡng",
// "Sữa chua Hoff",
// "Sữa chua Nestle",
// "Sữa chua tổ yến Nestle",
// "Sữa chua trân châu Hạ Long",
// "sữa chua uống betagen",
// "Sữa chua uống Nestle Yogu",
// "sữa chua uống susu",
// "Sữa chua uống tươi Vinamilk",
// "Sữa chua veyo",
// "Sữa chua Vinamilk Organic",
// "sữa chua vnm",
// "Sữa Đà Lạt",
// "sữa đặc ngôi sao phương nam",
// "sữa đặc ông thọ",
// "sữa đặc Vinamilk",
// "sữa đặc vinamilk tài lộc",
// "Sữa đậu đỏ vinamilk",
// "Sữa đậu nành Fami",
// "Sữa đậu nành Soya",
// "Sữa Đậu Nành Vinamilk",
// "Sữa đậu nành Vinasoy",
// "sữa fami",
// "Sữa gấu Nestle",
// "sữa hạnh nhân vinamilk",
// "sữa hạt óc chó vinamilk",
// "sữa Hilo",
// "Sữa Hoff",
// "sữa Kun",
// "sữa Lof",
// "sữa Mead Johnson",
// "Sữa Mộc Châu",
// "sữa nan",
// "sữa Nepro",
// "sữa Nestle",
// "Sữa Nestle Gấu",
// "sữa ngôi sao phương nam",
// "Sữa non Colos Fresh Milk",
// "sữa Nutramigen",
// "sữa Nuvi",
// "sữa Nuvita",
// "Sữa tắm LaPetal",
// "Sữa th",
// "Sữa tiệt trùng Nuvita",
// "sữa TOPKID",
// "sữa tươi Cô Gái Hà Lan",
// "Sữa Tươi Hữu Cơ Organic",
// "Sữa tươi vinamilk 100",
// "sữa tươi vnm",
// "sữa Varna",
// "Sữa veyo",
// "Sữa vinamilk Flex",
// "Sữa vinamilk Green Farm",
// "Sữa Vinamilk organic",
// "Sữa vinamilk Tổ Yến",
// "sữa vnm",
// "Sữa vnm ADM",
// "Sữa vnm flex",
// "Sữa vnm organic",
// "Sữa vnm Tổ Yến",
// "SuaBapNonLof",
// "SuaBaVi",
// "SuaCoGaiHaLan",
// "SữaĐặcÔngThọ",
// "SữađậunànhSoya",
// "suatuoicogaihalan",
// "sumo",
// "sumo yakiniku",
// "sumobbq",
// "Sun Group",
// "Sun Property",
// "Sun World",
// "Sun World Ba Na Hills",
// "Sun World Baden Moutain",
// "Sun World Fansipan Legend",
// "Sun World Ha Long",
// "Sun World Hạ Long",
// "Sun World HaLong",
// "Sun World Halong Complex",
// "sung group",
// "Sungroup",
// "Sunlight",
// "SUNRISE CITY",
// "SUNRISE CITYVIEW",
// "SUNRISE RIVERSIDE",
// "sunworld",
// "Super Bull",
// "Super Susu",
// "supermocaweek",
// "supra",
// "surf",
// "Sushi Hokkaido Sachi",
// "Sushi Kei",
// "Sushi Tei",
// "Sushiholic",
// "Sustainability",
// "susu vinamilk",
// "SVC",
// "SVC Holdings",
// "SVĐ Hàng Đẫy",
// "Synnex FPT",
// "syrena",
// "TAEL",
// "tài chính fe",
// "tài chính tiêu dùng shb finance",
// "TaiKhoanTichLuy",
// "TaiKhoanTraSau",
// "TaixeShopeeFood",
// "Talentnet Corporation",
// "Talentnet Việt Nam",
// "TalentnetCorporation",
// "tâm anh",
// "tam phúc lầu",
// "Tam Thái Tử",
// "Tamaya",
// "tamsugiaohangcungghn",
// "Tân Á",
// "Tân Hiệp Phát",
// "Tân Phú Việt Nam",
// "Tân Phú xuất khẩu bao bì",
// "TăngCườngMiễnDịch",
// "TânHiệpPhát",
// "Tantam100",
// "TantamviShop",
// "Tantaytantam",
// "Tạp chí Trading",
// "Tạp chí Tranding",
// "Tập đoàn Aeon",
// "tập đoàn CMC",
// "Tập đoàn FPT",
// "tập đoàn Grab",
// "tập đoàn hưng thịnh",
// "Tập đoàn Keppel",
// "Tập đoàn Lã Vong",
// "tập đoàn Masan",
// "Tập đoàn Nova",
// "tập đoàn TH",
// "tập đoàn thắng lợi group",
// "Tập đoàn Thế giới di động",
// "Tập đoàn Trung Nguyên Legend",
// "Tập đoàn Vạn Thịnh Phát",
// "tập đoàn xăng dầu việt nam",
// "tapchitrading",
// "TậpđoànBĐSAnGia",
// "TậpĐoànMặtTrời",
// "tapdoanxangdauvietnam",
// "Tasaki",
// "taychayghn",
// "taychaygiaohangnhanh",
// "taychayjnt",
// "taychaylazada",
// "taychayshopeeexpress",
// "taychayvietnampost",
// "tẩychayviettelpost",
// "tcb",
// "tcbs",
// "TCT Thương mại Xuất nhập khẩu Thanh Lễ",
// "TDI",
// "TDTT Phan Đình Phùng",
// "TeamMILO",
// "teaplus",
// "techcom",
// "techcombank",
// "TechcombankVN",
// "Teka",
// "tet bung xoa",
// "TetBungXoa",
// "TetDacBiet",
// "TetNgonHuHon",
// "TetSaleBungXoa",
// "Tettrieutyphu",
// "tgdd",
// "TGDĐ",
// "TGKC",
// "TH true ICE CREAM",
// "TH true JUICE",
// "TH True Milk",
// "TH True Nut",
// "TH True Rice",
// "TH True Tea",
// "TH true WATER",
// "THACO Agri",
// "THACO AGRICULTURE",
// "THACO AUTO",
// "THACO bus",
// "Thaco buýt",
// "THACO chăn nuôi",
// "THACO Chu Lai",
// "THACO Group",
// "THACO INDUSTRIES",
// "THACO nông nghiệp",
// "THACO tải",
// "THACO truck",
// "THACO Trường Hải",
// "ThacoGroup",
// "THALEXIM",
// "Tham Dôn",
// "tham rôn",
// "Tham Zôn",
// "ThanDeal",
// "thandeal chotha",
// "thandealchotha",
// "thắng lợi group",
// "thắng lợi land",
// "ThangPartyDealMeLy",
// "Thành Bưởi",
// "Thanh Lanh",
// "Thanh Le Corporation",
// "Thanhbuoi",
// "Thanhbuoi.com.vn",
// "Thanhbuoibus",
// "ThankYouVinamilk",
// "Thảo Điền investment",
// "ThaoNguyenXanhSuaMatLanh",
// "THCS FPT",
// "The Alley",
// "The Blue",
// "THE BOTANICA",
// "The Coffee House",
// "The Crown",
// "The Empire",
// "The Gangs",
// "Thế Giới Cà Phê",
// "THẾ GIỚI CÀ PHÊ TRUNG NGUYÊN LEGEND - HÀ NỘI",
// "thế giới di động",
// "Thế giới KC",
// "Thế Giới Kim Cuong",
// "The Global City",
// "the golden star",
// "The Metroline",
// "The Miami",
// "THE PARK AVENUE",
// "the peak garden",
// "the pot",
// "THE PRINCE RESIDENCE",
// "The Sakura",
// "the standard an gia",
// "The Standard Central Park",
// "THE SUN AVENUE",
// "The Tonkin",
// "THE TRESOR",
// "Thế_giới_kim_cương",
// "TheAddressOffice",
// "TheAlley",
// "thebrokers",
// "TheCoffeeHouse",
// "TheEverRich",
// "thegioididong.com",
// "thegioikimcuong",
// "ThếGiớiNuVi",
// "ThếGiớiSendo",
// "theGlobalCity",
// "TheGrandManhattan",
// "Thêm quà tặng tăng bảo vệ",
// "THEQUAKUN",
// "TheSongAnGia",
// "TheSongVungTau",
// "ThienDuongBoSuaMocChauMilk",
// "ThienDuongSamDep",
// "thienduyentienno",
// "Thiết bị y tế việt nhật JVC",
// "THILOGI",
// "Thiskyhall",
// "THISO",
// "thiso mall",
// "THISO Retail",
// "Thisofic",
// "THISOMall",
// "THISORETAIL",
// "ThoNhipVietNam",
// "THPT FPT",
// "THtrueBUTTER",
// "THtrueHerbal",
// "THtrueICECREAM",
// "THtrueJUICEmilk",
// "THtruemart",
// "THtruemilk",
// "THTrueTea",
// "THtrueYOGURT",
// "thu phí BOT",
// "thức uống năng lượng my joy",
// "thức uống năng lượng power",
// "thuchuthealthy",
// "Thung lũng Thanh Xuân",
// "THUNG LŨNG THANH XUÂN",
// "Thung Lũng Thanh Xuân - BIM Land",
// "thuốc VinFa",
// "Thượng Đình",
// "thủy sản bến tre",
// "ti ki",
// "tíc tốc",
// "tic tok",
// "tide",
// "Tiên Phong bank",
// "TienDiDong",
// "TienThongMinh",
// "TiepDealHaNhiet",
// "Tiepsucbactai",
// "Tiểu học FPT",
// "Tieu Yen Trinh",
// "tik tốc",
// "Tik Tok",
// "tiki",
// "Tiki ADS",
// "Tiki1111",
// "Tiki1212",
// "Tiki12Tuoi",
// "tiki273",
// "tikiads",
// "TikiBlackFriday",
// "TIKIChotdonrinhquaOct",
// "TikiConnect",
// "Tikihoisachonline",
// "tikimallads",
// "TikiNOW",
// "tikinow2h",
// "tikivn",
// "TikixHaAnhTuan",
// "TikTok",
// "tiktok ads",
// "TikTok shop",
// "TikTok shopping",
// "tiktokads",
// "TikTokaward",
// "TikToker",
// "TikTokfashion",
// "TikTokFilmContest",
// "tiktoklivevietnam",
// "TikTokshop",
// "TikTokshopping",
// "TikTokVietnam",
// "tiktokvn",
// "Tim Ho Wan",
// "times city",
// "Timezone",
// "Timezoner",
// "timzone",
// "tỉnh khánh hòa",
// "Tini world",
// "Tiniworld",
// "TLC",
// "TMCP Ngoại Thương",
// "TMF",
// "TNHH KDI",
// "TNHH phân phối FPT",
// "Tòa nhà 23 Láng Hạ",
// "Tòa nhà số 2 Phạm Ngọc Thạch",
// "toco",
// "tocotoco",
// "TOI rô ta",
// "Tokyo deli",
// "Tommy Hilfiger Vietnam",
// "Tommy Hilfiger VN",
// "Tổng công ty lâm nghiệp Việt Nam",
// "tổng công ty petrolimex",
// "Tổng đài FPT",
// "top top",
// "tóp tóp",
// "Topen Land",
// "TOPKID",
// "Topman Viet Nam",
// "Topman vietnam",
// "Topman VN",
// "Tops market",
// "Tops Market An Phú",
// "Tops Market Âu Cơ",
// "Tops Market Thảo Điền",
// "Topshop Viet Nam",
// "Topshop vietnam",
// "Topshop VN",
// "topsmarket",
// "toptop",
// "Toshiba",
// "Total Rewards",
// "toyhaisu",
// "Toyota Raize",
// "TP Bank",
// "TPB",
// "TPBANK",
// "TPC Vina",
// "trà atiso vfresh",
// "Trà dưa hấu vải HL",
// "Trà JOKKY",
// "Trà NutiZen",
// "Trà sữa Happy Vinamilk",
// "Trà Sữa Macchiato Không Độ",
// "trà sữa toco",
// "trà sữa tocotoco",
// "Trà Thanh Nhiệt Dr. Thanh",
// "Trà Vfresh",
// "Trà xanh C2",
// "Trà xanh Không Độ",
// "Trade demo",
// "TràJOKKY",
// "trạm thu phí BOT",
// "Trần Bá Trường Hải",
// "Trần Đức Huy",
// "Trân Oanh",
// "Trần Thị Hồng Bích",
// "TranBaDuong",
// "Trang sức BTMC",
// "Trang Sức DOJI",
// "Trang sức Lộc Phúc",
// "Trang_sức_DOJI",
// "TrangsucBTMC",
// "Trangsucdoji",
// "trangsuchuythanh",
// "TrangsucLocPhuc",
// "TràNutiZen",
// "TràsữaHappyVinamilk",
// "TràSữaMacchiatoKhôngĐộ",
// "TràThanhNhiệtDr.Thanh",
// "TràVfresh",
// "TràxanhC2",
// "TràxanhKhôngĐộ",
// "Trieudondonghanh",
// "Trinh Tiêu",
// "TrinhduyetCocCoc",
// "Trợ lý ảo Kiki",
// "Trợ lý giọng nói Kiki",
// "Trợ lý Kiki",
// "trợgiúpgiảiđápkhiếunại",
// "troicomuadungbobua",
// "TROPIC GARDEN",
// "TRUA0D",
// "truly việt",
// "Trung học Phổ thông FPT",
// "Trung nguyên",
// "Trung Nguyên Cafe",
// "Trung Nguyên Coffee",
// "Trung Nguyên Legend",
// "Trung Nguyên Legend Café",
// "Trung Sơn Pharma",
// "trung tâm apax",
// "trung tâm apollo",
// "trung tâm british council",
// "Trung tâm Chăm sóc Sức khoẻ Quốc tế Hạnh Phúc",
// "trung tâm ila",
// "Trung tâm thương mại GO",
// "trung tâm vus",
// "trung tâm yola",
// "trường APC",
// "TRUONG HAI AUTO",
// "trường ITC",
// "Trường Phúc Hải",
// "trường Văn Lang",
// "trường VLSC",
// "Truyền hình Cap",
// "Truyền hình FPT",
// "Truyền hình K",
// "Truyền hình K+",
// "Truyền hình số K",
// "Truyền hình Viettel",
// "TTTM GO",
// "tủ đông",
// "tủ lạnh",
// "tủ lạnh pana",
// "Tủ lạnh panasonic",
// "Tuần Châu",
// "Túi Starbuck",
// "tuithantai",
// "tuithantaidaichien",
// "TuoitrePVOIL",
// "Tương ớt Rồng Việt",
// "Tuyển dụng",
// "TV 360",
// "TV360",
// "Tvita",
// "TWIN COWS",
// "Twincows",
// "txkd",
// "TZ",
// "ubibenfoods",
// "UmBaLazRaMonNgon",
// "ứngdụngvietlott",
// "uniben",
// "UpliftingCommunities",
// "uptrades",
// "UuDaiDiemDen",
// "uudaiShopeePay",
// "ván sữa Bauer Petit",
// "ván sữa Burine",
// "ván sữa Fontana",
// "ván sữa Gotz",
// "ván sữa Heinz",
// "ván sữa Helio",
// "ván sữa Hoff",
// "ván sữa Humana",
// "ván sữa Lactes",
// "ván sữa Mixxi",
// "ván sữa Mixxo",
// "ván sữa Mon Blance",
// "ván sữa monte",
// "ván sữa nestle",
// "ván sữa nestlé",
// "vận tải bộ Petrolimex",
// "vận tải thủy petrolimex",
// "Vàng Mi Hồng",
// "váng monte",
// "váng sữa Bauer Petit",
// "váng sữa Burine",
// "váng sữa Fontana",
// "váng sữa Gotz",
// "váng sữa Heinz",
// "váng sữa Helio",
// "váng sữa Hoff",
// "váng sữa Humana",
// "váng sữa Lactes",
// "váng sữa Mixxi",
// "váng sữa Mixxo",
// "váng sữa Mon Blance",
// "váng sữa monte",
// "váng sữa nestle",
// "váng sữa nestlé",
// "vanlangsaigon",
// "Varna",
// "vay vốn fe",
// "vBareMetal",
// "VBDQ Sài Gòn",
// "vcb",
// "vCDN",
// "vCloudcam",
// "vCloudStack",
// "Vcontract",
// "vé số hà nội",
// "vé số khánh hòa",
// "Vé Xe Rẻ",
// "vedan",
// "Vega City",
// "Vega city Nha Trang",
// "Vegacity",
// "Vegetexco",
// "vESS",
// "VETC",
// "vexere",
// "Veyo Yogurt",
// "VEYOYogurt",
// "vfg",
// "vhm",
// "ví điện tử zalo",
// "ví shopee",
// "ví zalo",
// "vianco",
// "Vickini",
// "vidientuzalo",
// "vie on",
// "Viện Quản trị Kinh doanh FPT",
// "Viễn thông FPT",
// "viễn thông Quân đội",
// "VieON",
// "VieoOnSports",
// "viet credit",
// "Việt Hà",
// "Việt Hà Corp",
// "Viet Hung Phu",
// "Viet Nam National Petroleum Group",
// "Viet Street",
// "Việt Thái Plastchem",
// "vietcom bank",
// "vietcombank",
// "vietcredit",
// "vietel pay",
// "vietel post",
// "vietelpay",
// "vietin",
// "vietin bank",
// "vietinbank",
// "VIETLOTS",
// "Vietnam Grand Prix",
// "Vietnam Lottery Company",
// "vietnam post",
// "Vietnamdirect",
// "vietnampost",
// "Vietnamwork",
// "Vietnamworks",
// "Vietstarland",
// "vietstreet",
// "vietsugar",
// "Viettel",
// "viettel pay",
// "Viettel Post",
// "Viettel TV360 Box",
// "Viettel++",
// "ViettelCA",
// "ViettelMoney",
// "viettelpay",
// "viettelpost",
// "viettelpostnhanh",
// "viettin",
// "viettin bank",
// "viettinbank",
// "Viettlot",
// "vifon",
// "víganket",
// "Vigecam",
// "vigenz",
// "Vimoiganket",
// "vimomo",
// "Vin Bus",
// "Vin Fast",
// "vin home",
// "vin homes",
// "Vin ID",
// "vin mart",
// "vin mec",
// "Vin Shop",
// "Vin Smart",
// "vin smartcity",
// "Vin Vượng",
// "Vin wonders",
// "Vina giày",
// "Vina Giầy",
// "vina mil",
// "vina milk",
// "vina miu",
// "vina mjlk",
// "Vinafood",
// "Vinafood 2",
// "Vinafood2",
// "Vinafor",
// "Vinagiay",
// "Vinahost",
// "vinamik",
// "vinamil",
// "Vinamilk 100",
// "Vinamilk 100%",
// "Vinamilk 100% A2",
// "Vinamilk Abbott",
// "Vinamilk ADM",
// "Vinamilk Canxi Pro",
// "Vinamilk Colos Gold",
// "Vinamilk Delight",
// "Vinamilk Dielac",
// "Vinamilk Fino",
// "Vinamilk Flex",
// "Vinamilk Fonterra",
// "Vinamilk Fruit Love",
// "Vinamilk Green Farm",
// "Vinamilk ICY",
// "Vinamilk Icy chanh muối",
// "Vinamilk Kenko",
// "Vinamilk Mộc Châu",
// "Vinamilk My Joy",
// "Vinamilk Nhóc Kem",
// "vinamilk ông thọ",
// "Vinamilk Optimum",
// "Vinamilk Organic",
// "Vinamilk Organic Gold",
// "Vinamilk Oze",
// "Vinamilk Ozela",
// "Vinamilk Pedia Kenji",
// "Vinamilk Platinum",
// "Vinamilk Power",
// "Vinamilk Probeauty",
// "Vinamilk Ridielac",
// "Vinamilk Soy",
// "Vinamilk Subo",
// "Vinamilk Super Susu",
// "Vinamilk Sure Diecerna",
// "Vinamilk Sure Prevent",
// "vinamilk tài lộc",
// "Vinamilk Tổ Yến",
// "Vinamilk Trân Châu Đường Đen",
// "Vinamilk Trân Châu Hoàng Kim Vị Phô Mai",
// "Vinamilk Twincows",
// "Vinamilk Vfresh Juki",
// "Vinamilk Vietsugar",
// "Vinamilk Yakult",
// "Vinamilk Yoko",
// "Vinamilk Yoko Gold",
// "vinamilkDiecerna",
// "VinamilkGiacMoSuaViet",
// "VinamilkGreekYoghurt",
// "vinamilkhappymilktea",
// "VinamilkHero",
// "vinamilkitduong",
// "vinamilkoptimum",
// "VinamilkOptimumGold",
// "vinamilkorganic",
// "VinamilkProbi",
// "vinamilksupernut",
// "vinamilksurediecerna",
// "vinamilksusu",
// "vinamilkvfresh",
// "vinamilkzori",
// "vinamill",
// "vinamink",
// "vinamiu",
// "vinamjlk",
// "vinamlik",
// "vinaseed",
// "Vinasoy",
// "Vinawind",
// "VinBigData",
// "Vinbrain",
// "Vincharm",
// "Vincity",
// "vincomerce",
// "Vinconnect",
// "VinCSS",
// "VinDR",
// "VinDr PACS",
// "VinDS",
// "VinES",
// "VinFa",
// "VinFuture",
// "Vĩnh Phúc",
// "VinHMS",
// "vinhome",
// "vinhome ocean park",
// "vinhomegrandpark",
// "vinhomeoceanpark",
// "vinhomes",
// "Vinhomes Green Hạ Long",
// "Vinhomes Green Hạ Long Xanh",
// "Vinhomes Green Halong",
// "Vinhomes Hạ Long Xanh",
// "Vinhomes Hưng Yên",
// "Vinhomes The Crown",
// "Vinhomes The Empire",
// "Vinhomes VHOP 3",
// "Vinhomes VHOP2",
// "vinhomesbason",
// "vinhomesdanphuong",
// "VinhomesDragonBay",
// "VinhomesGallery",
// "vinhomesgrandpark",
// "VinhomesMarina",
// "VinhomesNewCenter",
// "VinhomesPriority",
// "VinhomesRiverside",
// "VinhomesRoyalCity",
// "vinhomessmartcity",
// "VinhomesStarCity",
// "VinhomesTimesCity",
// "VinhomesWestPoint",
// "VinhomesWonderPark",
// "VinhomesWonderParkDanPhuong",
// "VinhomWonderPark",
// "VinHR",
// "VinID",
// "VinKE",
// "Vinpearl",
// "Vinpearl Safari",
// "vinpearl wonder",
// "VinShop",
// "Vinsmart",
// "Vinsoftware",
// "Vintata",
// "VinTech",
// "VinUni",
// "Vinuniversity",
// "Vinunniversity",
// "VinWonders",
// "viso",
// "Vissan",
// "vitadairy",
// "Vitagrow",
// "vitrasau",
// "VIVA – ERS",
// "Viva Experience",
// "Viva Land",
// "Viva Land International Women’s Day Campaign",
// "VIVA LAND PEOPLE",
// "VivaLand",
// "VIVALAND GROUP",
// "VIVALANDGROUP",
// "Vivang",
// "vivangnhuy",
// "vivangruocloc",
// "Vivangtrolai",
// "vivangzalopay",
// "vizalo",
// "vjna milk",
// "vjnamilk",
// "vjnamjlk",
// "vMaas",
// "vMark",
// "vMarketing",
// "vn milk",
// "vn pay",
// "vn post",
// "VND",
// "VND Research",
// "VNDirect",
// "VNG",
// "VNGCorp",
// "VNGCorporation",
// "VNLife",
// "VNM",
// "vnm 100",
// "vnm 100%",
// "vnpay",
// "vnpaybill",
// "VNPAYInvoice",
// "vnpaypos",
// "VNPAYQR",
// "VNPAYSmartPOS",
// "VNpost",
// "vnpost.vn",
// "VNPT",
// "VNPTPAY",
// "vnticket",
// "vntopup",
// "vObject",
// "vObjectStorage",
// "Volvo an toàn",
// "Volvo Cars Việt Nam",
// "Volvo Hà Nội",
// "Volvo Hồ chí minh",
// "Volvo việt nam",
// "Voucher tích lũy 800K",
// "VP BANK",
// "VPB",
// "VPBANK",
// "VPS",
// "vServer",
// "Vsmart",
// "VTP",
// "VTVcab",
// "VTVcabOn",
// "Vũ Đình Đắc",
// "Vũ Đình Độ",
// "Vũ Ngọc Tú",
// "Vũ Thị Nguyệt VETC",
// "VuaShipHang",
// "vuatuoivuamoi",
// "VungFreeship",
// "vus",
// "Vuvu",
// "Warning Zone",
// "Warriors",
// "Washing Machine",
// "Watson",
// "Watsons",
// "WCM",
// "West Gate",
// "White Eagle",
// "wico",
// "Wifi công nghệ Mesh",
// "Wifi FPT",
// "wifi Viettel",
// "Wifi VNPT",
// "Wilson",
// "WILTON TOWER",
// "win wonder",
// "wincomerce",
// "wineco",
// "Winmart",
// "WINMART Phúc Long",
// "Woo Master",
// "WooMaster",
// "Wrap & Roll",
// "Wulao",
// "xăng",
// "xăng dầu petrolimex",
// "xangdau",
// "xangdauvietnam",
// "xangdauvn",
// "xây lắp thương mại petrolimex",
// "Xaynhatyphu",
// "Xe Fu Ta",
// "xe kia",
// "xe mazda",
// "xe ôm grab",
// "Xế vận hội Baemin",
// "xe volvo việt nam",
// "XE0D",
// "XE5K",
// "xekhachphuongtrang",
// "Xephuongtrang",
// "xevanhoiBaemin",
// "Xfast",
// "Xi măng Sông Gianh",
// "xì ting",
// "Xiaomi",
// "XinChaoGhienShopeePay",
// "XinchaoShopeeFood",
// "XinchaoShopeePay",
// "xổ đài hà nội",
// "xổ đài hcm",
// "xổ đài khánh hòa",
// "xổ đài sg",
// "xổ số hà nội",
// "xổ số hcm",
// "xổ số hồ chí minh",
// "xổ số khánh hòa",
// "xổ số sài gòn",
// "xổ số sg",
// "xổ số thủ đô",
// "xổ số tphcm",
// "xosokhanhhoa",
// "xosothudo",
// "xs khánh hòa",
// "xskt hà nội",
// "xskt hcm",
// "xskt hồ chí minh",
// "xskt khánh hòa",
// "xskt sài gòn",
// "xskt thủ đô",
// "xskthcm",
// "xskthn",
// "xsktkh",
// "Xúc xích CJ",
// "Xúc xích CP",
// "Xúc xích Dabaco",
// "Xúc xích Đức Việt",
// "Xúc xích Golf",
// "Xúc xích Heo Cao Bồi",
// "Xúc xích Le Gourmet",
// "Xúc Xích Red",
// "xúc xích trộn đều tamarind",
// "Xúc xích VISSAN",
// "Xúc xích winner",
// "y khoa hoàn mỹ",
// "Y tế việt nhật JVC",
// "Yakimono",
// "Yakult",
// "Yale",
// "YaMe",
// "YaMe Shop",
// "Yen Sushi",
// "YenSushi",
// "Yeo s",
// "yesmom",
// "Yeuminhdungdeminhdoi",
// "YeuNuHangLazada",
// "YMDDMD",
// "YODY",
// "Yogurt",
// "Yoko Gold",
// "yola",
// "yolo Delight",
// "Yomost",
// "Youtube Short",
// "YoutubeShort",
// "yutang",
// "Z.A.L.O.P.A.Y",
// "Zalo",
// "ZaloPay",
// "ZaloPayxIU",
// "Zamba Beer",
// "ZenityCapitaland",
// "zenpark",
// "ZIng TV",
// "ZingMP3",
// "zori vinamilk",
// "zott milk tiger",
// "Zumwhere Morden Izakaya",
// "FWD",
// "Prudential",
// "PRUOnline",
// "PRURewards",
// "ePru",
// "Pru",
// "ManulifeVietnam",
// "ManulifeMOVE",
// "MOVElavui",
// "ManuConnect",
// "M-Pro",
// "AIA+",
// "Vitality",
// "DaiichiLifeVietnam",
// "Generali",
// "SunLife",
// "mySunlife",
// "FWD insurance",
// "FWD bảo hiểm",
// "Công ty FWD",
// "FWD Care",
// "bảo hiểm",
// "bảo hiểm nhân thọ",
// "Điểm tựa tài chính",
// "Phụ nữ hiện đại",
// "Bộ 3 bảo vệ",
// "Bộ đôi tài sản 2.0",
// "Đón đầu thay đổi 3.0",
// "Sống trọn tương lai",
// "Con vươn xa 2.0",
// "Cả nhà vui khỏe",
// "Bảo hiểm tai nạn",
// "Bảo hiểm hỗ trợ viện phí",
// "Đại an minh tâm",
// "Bảo hiểm bệnh hiểm nghèo 2.0",
// "Bảo hiểm miễn đóng phí bệnh hiểm nghèo 2.0",
// "Bảo hiểm miễn đóng phí nâng cao 2.0",
// "Bảo hiểm sức khỏe 2.0",
// "Bảo hiểm tai nạn",
// "Bảo hiểm trợ cấp nằm viện",
// "Bảo hiểm tử vong và thương tật",
// "Nâng tầm vị thế 2.0",
// "Vững chắc tương lai",
// "Vị thế vững vàng",
// "Sống đầy mùa lễ hội",
// "Prudential insurance",
// "Prudential assurance",
// "Prudential PLC",
// "AIA Insurance",
// "Bảo hiểm AIA",
// "Bảo hiểm nhân thọ",
// "Cty AIA",
// "Công ty AIA",
// "Ct AIA",
// "AIA Exchange",
// "Nest by AIA",
// "Daiichi Life",
// "Dai-ichi",
// "Cty Daiichi",
// "Ichi Care",
// "Cty Generali",
// "Công ty Generali",
// "Sun Life",
// "SUN REWARD",
// "Công ty Sun Life",
// "Mẹ Siêu Nhân 2024",
// "Mẹ siêu nhân",
// "Supermom",
// "mesieunhan",
// "#MeSieuNhan",
// "#MeSieuNhan2024",
// "#SuperMom",
// "#supermonvietnam",
// "#PhamQuynhAnh",
// "#ThaoTrang",
// "#Emily",
// "#LamMinh",
// "KIDO",
// "KIDO Group",
// "tập đoàn KIDO",
// "KDC",
// "Tường An",
// "Dầu thực vật Tường An",
// "Vocarimex",
// "KIDO Nhà Bè",
// "bánh kẹo KIDO",
// "TFSVN",
// "taichinhtoyota",
// "Tài chính Toyota",
// "TFS",
// "#TFSVN",
// "#taichinhToyotaVietNam",
// "#TFS",
// "#dichvutaichinhToyota",
// "#vibuoctienmoi",
// "#saophainghi",
// "UNIS",
// "Trường UNIS",
// "UNIS Hanoi",
// "British International School Hanoi",
// "BIS Hanoi",
// "BIS",
// "Brighton college",
// "Trường Brighton",
// "Concordia",
// "Concordia International School Hanoi",
// "#UNISHanoi",
// "#BISHanoi",
// "#Brightoncollege",
// "#Concordiahanoi",
// "Vlasta",
// "#phobienbungsac",
// "Sầm Sơn Vlasta",
// "Dự án Vlasta",
// "KĐT Vlasta",
// "khu đô thị Vlasta",
// "nghỉ dưỡng Vlasta",
// "phố đi bộ Vlasta",
// "Tổ hợp đô thị biển Vlasta",
// "Blooming Vlasta",
// "Du lịch Vlasta",
// "#phobienbungsac Vlasta",
// "Hải Phòng Vlasta",
// "Thủy Nguyên Vlasta",
// "Vinhomes",
// "Vinhome",
// "Masteri",
// "Masterisehomes",
// "Masterise homes",
// "Sungroup",
// "Sun Group",
// "namlonggroup",
// "Nam Long Group",
// "Nam Long",
// "Flamingo Group",
// "flamingogroup",
// "Timo",
// "#timodigitalbank",
// "MB Bank",
// "Bee Rich",
// "MBBank",
// "MB",
// "Techcombank",
// "F@st eBank",
// "TCB",
// "VPBank NEO",
// "VPBank",
// "App yolo",
// "VPB",
// "VIB",
// "Ngân hàng điện tử VIB",
// "MyVIB",
// "Chuyên gia tài chính ảo",
// "TPBank",
// "TPBank digital",
// "TPBank Biz",
// "TPB",
// "Công ty 35",
// "CÔNG TY TNHH MTV ĐẦU TƯ PHÁT TRIỂN ĐỖ GIA QUẢNG NINH",
// "Công ty Đầu Tư Đỗ Gia",
// "Công ty Đỗ Gia Quảng Ninh",
// "CÔNG TY CỔ PHẦN ĐỒNG GIA",
// "Công ty Đồng Gia",
// "CÔNG TY TNHH TÂM THÀNH",
// "Công ty Tâm Thành",
// "#1212SANG0D",
// "#1212TOI0D",
// "#1212TRUA0D",
// "#12SIEUSHIP",
// "#AnCungTikTok",
// "#AOKHOACGIOYODY",
// "#appFuta",
// "#BAO50",
// "#baobimoi",
// "#Bésiêunhân",
// "#boovietnam",
// "#Cănhộdulịchbiển5saoVũngTàu",
// "#Canifa",
// "#caodangcntt",
// "#CaoDangNova",
// "#CaodangVietMy",
// "#Chienbinhtantam",
// "#Chuyenxehuongnghiep_ITC2023",
// "#CollabCollection2023",
// "#ColosDHA",
// "#coolmate",
// "#Cuoianhdi",
// "#DAITIEC12",
// "#daitiecgiaxinh",
// "#DCApp",
// "#DCFund",
// "#DCVFM",
// "#đènledvianco",
// "#dienquang",
// "#doibong_sangden",
// "#doibongsangden",
// "#DragonCapital",
// "#DragonX",
// "#Elise",
// "#enfa",
// "#FamiCanxi",
// "#G-smile",
// "#ghn",
// "#GHN_phốt",
// "#GHN10nam",
// "#ghnancap",
// "#ghnlàmănthiếutráchnhiệm",
// "#GHNlamhuhonghang",
// "#ghnlừađảo",
// "#ghnrutruot",
// "#ghntraohang",
// "#ghnvotrachnhiem",
// "#Giao_hàng_nhanh_gian_lận",
// "#giaohangnhanhantrom",
// "#giaohangnhanhgianlan",
// "#Gojek8K",
// "#Gsmile",
// "#hanhtrinhthanhxuancungshopeefood",
// "#HePhongThu1170",
// "#HMVietnam",
// "#hoangphucinternational",
// "#Hunglocvivang",
// "#IntoYourself",
// "#itstartsonTikTok",
// "#ivymoda",
// "#laithuskoda",
// "#learnontiktok",
// "#londonex",
// "#lookgoodfeelgood",
// "#macroequities",
// "#MangoVN",
// "#Mẹsiêuphàm",
// "#Milovietnam",
// "#MORNING12",
// "#moshopeedungshopeepay",
// "#MuaDealYeuThuong",
// "#MuonShopeeFoodToTinh",
// "#NANOptipro4",
// "#nemfahsion",
// "#neotrades",
// "#NhungDoaHoaKienCuong",
// "#Ninomaxx",
// "#Ninomaxx_Concept",
// "#NovaCollege",
// "#NowdoitenthanhShopeeFood",
// "#NowShopeeFood1808",
// "#phốtghn",
// "#PolyKBeauty",
// "#rangdong",
// "#SHEINVN",
// "#ShopeeFood1010",
// "#ShopeeFood1111",
// "#ShopeeFood1212",
// "#ShopeeFood1402",
// "#ShopeeFood1501",
// "#ShopeeFood99",
// "#SIEUDEAL",
// "#SIEUSALE",
// "#SIEUTIEC0D",
// "#Skoda",
// "#skodavietnam",
// "#SOHO",
// "#SPFOOD122",
// "#SPFOOD5",
// "#SPFOOD82",
// "#SữaĐặcÔngThọ",
// "#TaiKhoanTichLuy",
// "#TaiKhoanTraSau",
// "#Tantam100",
// "#TantamviShop",
// "#Tantaytantam",
// "#TậpđoànBĐSAnGia",
// "#TetNgonHuHon",
// "#thunglungthanhxuan",
// "#tiktoklivevietnam",
// "#TikTokVietnam",
// "#tiktokvn",
// "#TLC",
// "#TommyJeansVN",
// "#topmanVN",
// "#Trieudondonghanh",
// "#trợgiúpgiảiđápkhiếunại",
// "#tuithantai",
// "#vanlangsaigon",
// "#vianco",
// "#viancolighting",
// "#Vivang",
// "#Vivangtrolai",
// "#vivangzalopay",
// "#vuatuoivuamoi",
// "#wolfooincanifa",
// "#xekhachphuongtrang",
// "#Xephuongtrang",
// "#XinchaoShopeeFood",
// "#yesmom",
// "#Yeuminhdungdeminhdoi",
// "#yody",
// "#YODYJEAN",
// "#YODYOFFICE",
// "#YODYxMYTAM",
// "#YODYYEU",
// "#FWDBảohiểmdễhiểu",
// "#FWDSốngđầytừhômnay",
// "#FWDSớmbảovệ",
// "#FWDBaohiemdehieu",
// "#FWDSốngdầytừhômnay",
// "#FWDSombaove",
// "#FWDCelebrateLivingStory",
// "#FWDTimetoPlay",
// "#FWDAgencyKickoff2024",
// "#TrailblazerAwards2024",
// "#FWD",
// "#Mình_luôn_cần_nhau",
// "#Prudential",
// "#Tết_chỉ_cần_có_nhau",
// "#Người_Lạ_Tôi_Cần",
// "#ManulifeVietNam",
// "#ActsofKindness",
// "#quymomanulife",
// "#AIA",
// "#NestbyAIA",
// "#AIAExchange",
// "#AIAVietnam",
// "#AIAVitality",
// "#exchangebyaia",
// "#tuhaohanhtrinhtoichon",
// "#DaiichiLife",
// "#DaiichiLifeVietnam",
// "#Hiểuđúngbảovệđủ",
// "#DaiichiConnect",
// "#GeneraliVietnam",
// "#SốngNhưÝ",
// "#SunLifeVietnam",
// "#LifeIsBrighterUnderTheSun",
// "#KeHoachLacQuan",
// "#SUNvungvang",
// "#agencynextmove",
// "#Ganbodailau",


]
console.log(urlVdideo1.length)
let addQueue1 = 0
for(let i=0;i<urlVdideo1.length;i++){
    const urlPost = await schemaurlpost.find({keyword:`${urlVdideo1[i]}`})
    console.log(urlPost.length)
if(urlPost.length ==0){
        if(addQueue1<7){
            addQueue1++
            queueKeyWord.add({keyword:`${urlVdideo1[i]}`,addQueued:0})
            console.log({keyword:`${urlVdideo1[i]}`})
            await delay(10000)

        }else{
            queueKeyWord.add({keyword:`${urlVdideo1[i]}`,addQueued:0})
            console.log({keyword:`${urlVdideo1[i]}`,addQueued:0})
        }
       
}
}

// const urlVdideo = await schemakeyword.find({}).limit(999)
// console.log(urlVdideo.length)
// let addQueue = 0
// for(let i=0;i<urlVdideo.length;i++){
//     const urlPost = await schemaurlpost.find({keyword:`${urlVdideo[i].keyword}`})
//     console.log(urlPost.length)
//     // if(urlPost.length ==0 ){
        
//         if(addQueue<7){
//                         addQueue++
//                         queueKeyWord.add({keyword:`${urlVdideo[i].keyword}`,addQueued:0})
//                         console.log({keyword:`${urlVdideo[i].keyword}`,addQueued:0})
//                         await delay(10000)
            
//                     }else{
//                         queueKeyWord.add({keyword:`${urlVdideo[i].keyword}`,addQueued:0})
//                         console.log({keyword:`${urlVdideo[i].keyword}`,addQueued:0})
//                     }
//     // } 

// }


// await queueKeyWord.obliterate({ force: true });
